// =============================================================
// Problem Seed Data - Linux (categoryId: 2)
// 총 330개 (10 subCategories × 33 problems)
// 각 subCategory당 33개 (EASY:11, NORMAL:11, HARD:11)
// =============================================================
// subCategoryId 매핑:
// Shell:11, File:12, Permissions:13, Process:14, Network:15,
// System:16, User:17, Disk:18, Package:19, Cron:20
// =============================================================

import { ProblemSeedData } from './git';

export const problems: ProblemSeedData[] = [
  // =============================================
  // Linux > Shell (categoryId: 2, subCategoryId: 11)
  // =============================================
  // --- EASY (11) ---
  {
    difficulty: 'EASY',
    title: '현재 디렉토리 확인',
    text: '현재 작업 중인 디렉토리의 절대 경로를 출력하는 명령어는?',
    answer: 'pwd',
    explanation:
      '`pwd`(print working directory)는 현재 작업 디렉토리의 전체 절대 경로를 출력합니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'EASY',
    title: '화면 지우기',
    text: '터미널 화면을 깨끗하게 지우는 명령어는?',
    answer: 'clear',
    explanation: '`clear`는 터미널 화면의 모든 출력을 지우고 커서를 상단으로 이동시킵니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'EASY',
    title: '문자열 출력',
    text: '터미널에 "Hello World"를 출력하는 명령어는?',
    answer: 'echo "Hello World"',
    explanation: '`echo`는 뒤에 오는 문자열을 표준 출력으로 출력합니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'EASY',
    title: '명령어 이력 확인',
    text: '이전에 실행한 명령어 이력을 확인하는 명령어는?',
    answer: 'history',
    explanation:
      '`history`는 현재 쉘 세션과 이전 세션에서 실행한 명령어 목록을 번호와 함께 출력합니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'EASY',
    title: '명령어 매뉴얼 확인',
    text: '`ls` 명령어의 사용법과 옵션을 확인하는 매뉴얼 명령어는?',
    answer: 'man ls',
    explanation:
      '`man`은 명령어의 매뉴얼 페이지를 표시합니다. 사용법, 옵션, 예제 등을 확인할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'EASY',
    title: '별칭 확인',
    text: '현재 설정된 모든 쉘 별칭(alias)을 확인하는 명령어는?',
    answer: 'alias',
    explanation: '`alias`를 인자 없이 실행하면 현재 설정된 모든 별칭 목록을 출력합니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'EASY',
    title: '환경변수 확인',
    text: '현재 설정된 모든 환경변수를 출력하는 명령어는?',
    answer: 'env',
    explanation: '`env`는 현재 쉘에 설정된 모든 환경변수와 그 값을 출력합니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'EASY',
    title: '명령어 위치 확인',
    text: '`python3` 실행 파일의 경로를 확인하는 명령어는?',
    answer: 'which python3',
    explanation: '`which`는 `PATH`에서 지정된 명령어의 실행 파일 경로를 찾아 출력합니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'EASY',
    title: '사용 중인 쉘 확인',
    text: '현재 사용 중인 쉘의 경로를 확인하기 위해 출력해야 하는 환경변수는?',
    answer: 'echo $SHELL',
    explanation: '`$SHELL` 환경변수에는 현재 사용자의 기본 쉘 경로가 저장되어 있습니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'EASY',
    title: '홈 디렉토리 이동',
    text: '어디서든 홈 디렉토리로 이동하는 가장 간단한 명령어는?',
    answer: 'cd',
    explanation: '`cd`를 인자 없이 실행하면 현재 사용자의 홈 디렉토리(`~`)로 이동합니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'EASY',
    title: '이전 디렉토리 이동',
    text: '직전에 있었던 디렉토리로 다시 이동하는 명령어는?',
    answer: 'cd -',
    explanation:
      '`cd -`는 이전 작업 디렉토리로 전환합니다. 두 디렉토리를 번갈아 작업할 때 유용합니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  // --- NORMAL (11) ---
  {
    difficulty: 'NORMAL',
    title: '별칭 설정',
    text: '`ll`을 `ls -la`의 별칭으로 설정하는 명령어는?',
    answer: "alias ll='ls -la'",
    explanation:
      '`alias`로 자주 사용하는 명령어의 단축어를 설정할 수 있습니다. 현재 세션에서만 유효하며, 영구 적용은 `.bashrc`에 추가해야 합니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'NORMAL',
    title: '환경변수 설정',
    text: '`APP_ENV` 환경변수를 "production"으로 설정하고 하위 프로세스에도 전달되게 하는 명령어는?',
    answer: 'export APP_ENV=production',
    explanation:
      '`export`는 변수를 환경변수로 설정하여 현재 쉘과 하위 프로세스에서 모두 사용할 수 있게 합니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'NORMAL',
    title: '파이프라인',
    text: '`ps aux` 결과에서 "nginx" 문자열이 포함된 줄만 필터링하는 명령어는?',
    answer: 'ps aux | grep nginx',
    explanation:
      '파이프(`|`)는 앞 명령어의 표준 출력을 뒤 명령어의 표준 입력으로 전달합니다. `grep`으로 특정 패턴을 필터링합니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'NORMAL',
    title: '출력 리다이렉션',
    text: '`echo "hello"`의 출력을 `output.txt` 파일에 저장(덮어쓰기)하는 명령어는?',
    answer: 'echo "hello" > output.txt',
    explanation: '`>`는 표준 출력을 파일로 리다이렉트합니다. 파일이 존재하면 내용을 덮어씁니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'NORMAL',
    title: '출력 추가 리다이렉션',
    text: '`echo "world"`의 출력을 `output.txt` 파일 끝에 추가하는 명령어는?',
    answer: 'echo "world" >> output.txt',
    explanation:
      '`>>`는 표준 출력을 파일 끝에 추가(append)합니다. 기존 내용을 유지하면서 새 내용을 덧붙입니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'NORMAL',
    title: '명령어 연속 실행',
    text: '`mkdir build` 성공 시에만 `cd build`를 실행하는 명령어 연결 방법은?',
    answer: 'mkdir build && cd build',
    explanation: '`&&`는 앞 명령어가 성공(종료 코드 0)한 경우에만 뒤 명령어를 실행합니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'NORMAL',
    title: '에러 리다이렉션',
    text: '`find / -name "*.log"` 실행 시 에러 메시지를 숨기고 정상 결과만 보는 명령어는?',
    answer: 'find / -name "*.log" 2>/dev/null',
    explanation:
      '`2>/dev/null`은 표준 에러(fd 2)를 `/dev/null`로 리다이렉트하여 에러 메시지를 버립니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'NORMAL',
    title: '백그라운드 실행',
    text: '`sleep 100` 명령어를 백그라운드에서 실행하는 명령어는?',
    answer: 'sleep 100 &',
    explanation:
      '명령어 끝에 `&`를 붙이면 백그라운드에서 실행됩니다. 쉘 프롬프트가 즉시 반환되어 다른 작업을 할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'NORMAL',
    title: '명령어 치환',
    text: '현재 날짜를 `today` 변수에 저장하는 명령어는?',
    answer: 'today=$(date)',
    explanation: '`$()`는 명령어 치환으로, 괄호 안의 명령어 실행 결과를 변수에 할당합니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'NORMAL',
    title: 'PATH에 디렉토리 추가',
    text: '`/opt/bin` 디렉토리를 `PATH` 환경변수에 추가하는 명령어는?',
    answer: 'export PATH=$PATH:/opt/bin',
    explanation:
      '기존 `$PATH` 값에 콜론(`:`)으로 구분하여 새 경로를 추가합니다. 이후 해당 디렉토리의 실행 파일을 경로 없이 실행할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'NORMAL',
    title: '종료 코드 확인',
    text: '직전에 실행한 명령어의 종료 코드를 확인하는 명령어는?',
    answer: 'echo $?',
    explanation:
      '`$?`는 직전 명령어의 종료 코드를 저장하는 특수 변수입니다. 0은 성공, 그 외는 실패를 의미합니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  // --- HARD (11) ---
  {
    difficulty: 'HARD',
    title: 'Here Document',
    text: '여러 줄의 텍스트를 `config.txt` 파일에 작성하기 위한 here document 시작 구문은?',
    answer: 'cat << EOF > config.txt',
    explanation:
      '`<< EOF`는 here document로, `EOF`가 나올 때까지의 모든 줄을 표준 입력으로 전달합니다. `>`와 함께 사용하면 파일에 저장됩니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'HARD',
    title: 'xargs 활용',
    text: '`find . -name "*.tmp"` 결과의 모든 파일을 `rm`으로 삭제하는 명령어는?',
    answer: 'find . -name "*.tmp" | xargs rm',
    explanation:
      '`xargs`는 표준 입력으로 받은 항목들을 뒤의 명령어의 인자로 전달합니다. 대량의 파일을 효율적으로 처리할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'HARD',
    title: 'tee 명령어',
    text: '`ls -la`의 결과를 화면에 출력하면서 동시에 `output.txt`에도 저장하는 명령어는?',
    answer: 'ls -la | tee output.txt',
    explanation:
      '`tee`는 표준 입력을 표준 출력과 파일 모두에 전달합니다. 화면 확인과 파일 저장을 동시에 할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'HARD',
    title: '변수 기본값 설정',
    text: '`DB_HOST` 변수가 설정되지 않은 경우 "localhost"를 기본값으로 사용하는 쉘 구문은?',
    answer: '${DB_HOST:-localhost}',
    explanation:
      '`${VAR:-default}`는 변수가 설정되지 않았거나 비어있을 때 기본값을 반환합니다. 변수 자체를 변경하지는 않습니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'HARD',
    title: 'exec 리다이렉션',
    text: '현재 쉘의 모든 이후 표준 출력을 `session.log` 파일로 리다이렉트하는 명령어는?',
    answer: 'exec > session.log',
    explanation:
      '`exec > session.log`는 현재 쉘의 파일 디스크립터를 변경하여 이후 모든 표준 출력을 파일로 리다이렉트합니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'HARD',
    title: 'named pipe 생성',
    text: '`mypipe`라는 이름의 named pipe(FIFO)를 생성하는 명령어는?',
    answer: 'mkfifo mypipe',
    explanation:
      '`mkfifo`는 named pipe를 생성합니다. 서로 다른 프로세스 간 데이터를 파이프라인 없이 파일 인터페이스로 전달할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'HARD',
    title: '산술 연산',
    text: '쉘에서 `count` 변수에 현재 값에 5를 더하여 저장하는 명령어는?',
    answer: 'count=$((count + 5))',
    explanation:
      '`$(( ))`는 쉘에서 산술 연산을 수행합니다. 변수 참조 시 `$` 접두사가 필요 없습니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'HARD',
    title: 'trap 시그널 처리',
    text: '스크립트 종료 시 `/tmp/lockfile`을 자동으로 삭제하도록 trap을 설정하는 명령어는?',
    answer: 'trap "rm -f /tmp/lockfile" EXIT',
    explanation:
      '`trap`은 특정 시그널 수신 시 실행할 명령을 설정합니다. `EXIT`는 스크립트 정상/비정상 종료 시 모두 실행됩니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'HARD',
    title: '프로세스 치환',
    text: '두 디렉토리의 파일 목록을 `diff`로 비교하되, 임시 파일 없이 수행하는 명령어는?',
    answer: 'diff <(ls dir1) <(ls dir2)',
    explanation:
      '`<()`는 프로세스 치환으로, 명령어 출력을 임시 파일 디스크립터로 전달합니다. 임시 파일 없이 두 명령어 결과를 비교할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'HARD',
    title: '서브쉘 실행',
    text: '현재 디렉토리를 유지하면서 서브쉘에서 `cd /tmp && ls`를 실행하는 구문은?',
    answer: '(cd /tmp && ls)',
    explanation:
      '`()`로 감싸면 서브쉘에서 실행됩니다. 서브쉘의 디렉토리 변경은 부모 쉘에 영향을 주지 않습니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  {
    difficulty: 'HARD',
    title: '표준출력과 에러 동시 리다이렉션',
    text: '명령어의 표준 출력과 표준 에러를 모두 `all.log` 파일에 저장하는 명령어는?',
    answer: 'command > all.log 2>&1',
    explanation:
      '`> all.log`는 표준 출력을 파일로, `2>&1`은 표준 에러(fd 2)를 표준 출력(fd 1)과 같은 곳으로 리다이렉트합니다.',
    categoryId: 2,
    subCategoryId: 11,
  },
  // =============================================
  // Linux > File (categoryId: 2, subCategoryId: 12)
  // =============================================
  // --- EASY (11) ---
  {
    difficulty: 'EASY',
    title: '파일 목록 보기',
    text: '현재 디렉토리의 파일과 디렉토리 목록을 출력하는 명령어는?',
    answer: 'ls',
    explanation: '`ls`는 현재 디렉토리의 파일과 디렉토리 이름을 나열합니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'EASY',
    title: '상세 파일 목록',
    text: '현재 디렉토리의 파일을 권한, 소유자, 크기, 날짜 등 상세 정보와 함께 보는 명령어는?',
    answer: 'ls -l',
    explanation:
      '`ls -l`은 파일의 권한, 소유자, 그룹, 크기, 수정일 등 상세 정보를 포함하여 목록을 출력합니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'EASY',
    title: '숨김 파일 포함 목록',
    text: '숨김 파일(`.`으로 시작하는 파일)을 포함하여 모든 파일을 보는 명령어는?',
    answer: 'ls -a',
    explanation: '`ls -a`는 `.`으로 시작하는 숨김 파일을 포함한 모든 파일을 표시합니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'EASY',
    title: '디렉토리 생성',
    text: '`project`라는 이름의 디렉토리를 생성하는 명령어는?',
    answer: 'mkdir project',
    explanation: '`mkdir`(make directory)은 지정한 이름의 새 디렉토리를 생성합니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'EASY',
    title: '파일 복사',
    text: '`file.txt`를 `backup.txt`로 복사하는 명령어는?',
    answer: 'cp file.txt backup.txt',
    explanation: '`cp`(copy)는 파일을 복사합니다. 첫 번째 인자가 원본, 두 번째가 대상입니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'EASY',
    title: '파일 이동',
    text: '`report.txt`를 `archive/` 디렉토리로 이동하는 명령어는?',
    answer: 'mv report.txt archive/',
    explanation: '`mv`(move)는 파일을 다른 위치로 이동합니다. 파일 이름 변경에도 사용됩니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'EASY',
    title: '파일 삭제',
    text: '`temp.txt` 파일을 삭제하는 명령어는?',
    answer: 'rm temp.txt',
    explanation:
      '`rm`(remove)은 파일을 삭제합니다. 삭제된 파일은 복구가 어려우므로 주의가 필요합니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'EASY',
    title: '파일 내용 보기',
    text: '`readme.txt` 파일의 전체 내용을 화면에 출력하는 명령어는?',
    answer: 'cat readme.txt',
    explanation: '`cat`(concatenate)은 파일 내용을 표준 출력으로 출력합니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'EASY',
    title: '빈 파일 생성',
    text: '`newfile.txt`라는 빈 파일을 생성하는 명령어는?',
    answer: 'touch newfile.txt',
    explanation:
      '`touch`는 파일이 없으면 빈 파일을 생성하고, 이미 존재하면 수정 시간을 갱신합니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'EASY',
    title: '파일 이름 변경',
    text: '`old.txt` 파일의 이름을 `new.txt`로 변경하는 명령어는?',
    answer: 'mv old.txt new.txt',
    explanation: '`mv`는 파일 이동뿐 아니라 같은 디렉토리에서 이름을 변경하는 데도 사용됩니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'EASY',
    title: '파일 앞부분 보기',
    text: '`log.txt` 파일의 처음 10줄을 출력하는 명령어는?',
    answer: 'head log.txt',
    explanation: '`head`는 파일의 처음 부분을 출력합니다. 기본적으로 처음 10줄을 보여줍니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  // --- NORMAL (11) ---
  {
    difficulty: 'NORMAL',
    title: '중첩 디렉토리 생성',
    text: '`a/b/c` 경로의 디렉토리를 중간 디렉토리 포함하여 한 번에 생성하는 명령어는?',
    answer: 'mkdir -p a/b/c',
    explanation: '`mkdir -p`는 경로 상의 존재하지 않는 중간 디렉토리를 자동으로 생성합니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'NORMAL',
    title: '디렉토리 재귀 복사',
    text: '`src/` 디렉토리를 하위 파일과 함께 `backup/`으로 복사하는 명령어는?',
    answer: 'cp -r src/ backup/',
    explanation: '`cp -r`(recursive)은 디렉토리와 하위 내용을 재귀적으로 복사합니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'NORMAL',
    title: '디렉토리 재귀 삭제',
    text: '`old_project/` 디렉토리와 하위 모든 파일을 확인 없이 삭제하는 명령어는?',
    answer: 'rm -rf old_project/',
    explanation: '`rm -rf`에서 `-r`은 재귀 삭제, `-f`는 확인 없이 강제 삭제합니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'NORMAL',
    title: '파일 검색',
    text: '`/home` 디렉토리에서 이름이 `*.log`인 파일을 찾는 명령어는?',
    answer: 'find /home -name "*.log"',
    explanation:
      '`find`는 디렉토리 트리를 재귀적으로 탐색하여 조건에 맞는 파일을 찾습니다. `-name`은 파일 이름 패턴으로 검색합니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'NORMAL',
    title: '파일 끝부분 보기',
    text: '`server.log` 파일의 마지막 20줄을 출력하는 명령어는?',
    answer: 'tail -n 20 server.log',
    explanation:
      '`tail -n 20`은 파일의 마지막 20줄을 출력합니다. `-n` 옵션으로 줄 수를 지정할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'NORMAL',
    title: '실시간 로그 모니터링',
    text: '`app.log` 파일에 새로 추가되는 내용을 실시간으로 확인하는 명령어는?',
    answer: 'tail -f app.log',
    explanation:
      '`tail -f`(follow)는 파일 끝에 새로운 내용이 추가될 때마다 실시간으로 출력합니다. 로그 모니터링에 필수적입니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'NORMAL',
    title: '파일 내 문자열 검색',
    text: '`config.txt` 파일에서 "port" 문자열이 포함된 줄을 찾는 명령어는?',
    answer: 'grep "port" config.txt',
    explanation: '`grep`은 파일에서 지정된 패턴과 일치하는 줄을 찾아 출력합니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'NORMAL',
    title: '심볼릭 링크 생성',
    text: '`/var/log/app.log` 파일의 심볼릭 링크를 현재 디렉토리에 `app.log`로 생성하는 명령어는?',
    answer: 'ln -s /var/log/app.log app.log',
    explanation:
      '`ln -s`는 심볼릭(소프트) 링크를 생성합니다. 원본 파일의 경로를 가리키는 바로가기 역할을 합니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'NORMAL',
    title: '파일 종류 확인',
    text: '`data.bin` 파일의 종류(텍스트, 바이너리, 이미지 등)를 확인하는 명령어는?',
    answer: 'file data.bin',
    explanation:
      '`file`은 파일의 매직 넘버를 분석하여 파일 종류를 판별합니다. 확장자가 아닌 실제 내용을 기반으로 판단합니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'NORMAL',
    title: '줄 수 세기',
    text: '`data.csv` 파일의 줄 수를 세는 명령어는?',
    answer: 'wc -l data.csv',
    explanation: '`wc -l`(word count, lines)은 파일의 줄 수를 출력합니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'NORMAL',
    title: '파일 정렬 출력',
    text: '`names.txt` 파일의 내용을 알파벳 순으로 정렬하여 출력하는 명령어는?',
    answer: 'sort names.txt',
    explanation:
      '`sort`는 파일의 각 줄을 알파벳 순으로 정렬하여 출력합니다. 원본 파일은 변경되지 않습니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  // --- HARD (11) ---
  {
    difficulty: 'HARD',
    title: '크기 기준 파일 검색',
    text: '`/var` 디렉토리에서 100MB 이상인 파일을 찾는 명령어는?',
    answer: 'find /var -size +100M',
    explanation:
      '`find -size +100M`은 100MB보다 큰 파일을 검색합니다. `+`는 초과, `-`는 미만을 의미합니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'HARD',
    title: '수정 시간 기준 검색',
    text: '현재 디렉토리에서 최근 7일 이내에 수정된 파일만 찾는 명령어는?',
    answer: 'find . -mtime -7',
    explanation:
      '`-mtime -7`은 수정 시간이 7일 이내인 파일을 검색합니다. `-mtime +7`은 7일 이전 파일을 찾습니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'HARD',
    title: '재귀 문자열 검색',
    text: '`/etc/` 디렉토리 하위의 모든 파일에서 "127.0.0.1" 문자열을 재귀적으로 검색하는 명령어는?',
    answer: 'grep -r "127.0.0.1" /etc/',
    explanation: '`grep -r`(recursive)은 디렉토리 하위의 모든 파일을 재귀적으로 검색합니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'HARD',
    title: 'find exec 조합',
    text: '`/tmp`에서 `.tmp` 확장자 파일을 찾아 각각 삭제하는 명령어는?',
    answer: 'find /tmp -name "*.tmp" -exec rm {} \\;',
    explanation:
      '`-exec rm {} \\;`는 찾은 각 파일에 대해 `rm` 명령을 실행합니다. `{}`는 찾은 파일명으로 치환됩니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'HARD',
    title: 'tar 아카이브 생성',
    text: '`project/` 디렉토리를 gzip 압축된 `project.tar.gz` 아카이브로 생성하는 명령어는?',
    answer: 'tar czf project.tar.gz project/',
    explanation: '`tar czf`에서 `c`는 생성(create), `z`는 gzip 압축, `f`는 파일 이름 지정입니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'HARD',
    title: 'tar 아카이브 해제',
    text: '`backup.tar.gz` 파일을 현재 디렉토리에 압축 해제하는 명령어는?',
    answer: 'tar xzf backup.tar.gz',
    explanation: '`tar xzf`에서 `x`는 추출(extract), `z`는 gzip 해제, `f`는 파일 지정입니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'HARD',
    title: 'sed 문자열 치환',
    text: '`config.txt` 파일에서 "localhost"를 "192.168.1.1"로 모두 치환하여 파일을 직접 수정하는 명령어는?',
    answer: "sed -i 's/localhost/192.168.1.1/g' config.txt",
    explanation:
      "`sed -i 's/old/new/g'`는 파일 내 모든 일치 항목을 치환합니다. `-i`는 파일을 직접 수정(in-place)하며, `g`는 줄당 모든 일치를 치환합니다.",
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'HARD',
    title: 'awk 특정 필드 추출',
    text: '`/etc/passwd` 파일에서 콜론(`:`)을 구분자로 첫 번째 필드(사용자명)만 출력하는 명령어는?',
    answer: "awk -F: '{print $1}' /etc/passwd",
    explanation:
      '`awk -F:`는 구분자를 콜론으로 설정하고, `{print $1}`은 첫 번째 필드를 출력합니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'HARD',
    title: '중복 제거',
    text: '`data.txt` 파일에서 중복된 줄을 제거하고 고유한 줄만 출력하는 명령어는?',
    answer: 'sort data.txt | uniq',
    explanation:
      '`uniq`는 연속된 중복 줄을 제거합니다. `sort`와 함께 사용해야 비연속 중복도 제거됩니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'HARD',
    title: '디렉토리만 검색',
    text: '`/home`에서 이름이 "config"인 디렉토리만 찾는 명령어는?',
    answer: 'find /home -type d -name "config"',
    explanation:
      '`-type d`는 디렉토리만 검색 대상으로 제한합니다. `-type f`는 일반 파일만 검색합니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  {
    difficulty: 'HARD',
    title: '특정 열 기준 정렬',
    text: '`data.csv` 파일을 쉼표(`,`) 구분의 두 번째 필드 기준으로 숫자 정렬하는 명령어는?',
    answer: 'sort -t, -k2 -n data.csv',
    explanation:
      '`-t,`는 구분자를 쉼표로, `-k2`는 두 번째 필드 기준, `-n`은 숫자 정렬을 지정합니다.',
    categoryId: 2,
    subCategoryId: 12,
  },
  // =============================================
  // Linux > Permissions (categoryId: 2, subCategoryId: 13)
  // =============================================
  // --- EASY (11) ---
  {
    difficulty: 'EASY',
    title: '파일 권한 확인',
    text: '`script.sh` 파일의 권한 정보를 확인하는 명령어는?',
    answer: 'ls -l script.sh',
    explanation:
      '`ls -l`은 파일의 권한, 소유자, 그룹, 크기, 수정일 등 상세 정보를 표시합니다. 권한은 `rwxr-xr-x` 형식으로 표시됩니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'EASY',
    title: '실행 권한 부여',
    text: '`deploy.sh` 파일에 실행 권한을 추가하는 명령어는?',
    answer: 'chmod +x deploy.sh',
    explanation:
      '`chmod +x`는 파일에 실행(execute) 권한을 추가합니다. 모든 사용자(소유자, 그룹, 기타)에게 실행 권한이 부여됩니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'EASY',
    title: '소유자 변경',
    text: '`app.log` 파일의 소유자를 `www-data`로 변경하는 명령어는?',
    answer: 'chown www-data app.log',
    explanation: '`chown`(change owner)은 파일의 소유자를 변경합니다. 보통 root 권한이 필요합니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'EASY',
    title: '숫자 모드 권한 설정',
    text: '`config.txt` 파일의 권한을 소유자 읽기/쓰기, 그룹 읽기, 기타 없음으로 설정하는 명령어는?',
    answer: 'chmod 640 config.txt',
    explanation:
      '`640`에서 6(rw-)은 소유자, 4(r--)는 그룹, 0(---)은 기타 사용자의 권한입니다. r=4, w=2, x=1을 합산합니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'EASY',
    title: '쓰기 권한 제거',
    text: '`important.txt` 파일에서 모든 사용자의 쓰기 권한을 제거하는 명령어는?',
    answer: 'chmod a-w important.txt',
    explanation: '`a-w`에서 `a`는 모든 사용자(all), `-`는 제거, `w`는 쓰기 권한을 의미합니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'EASY',
    title: '그룹 변경',
    text: '`shared.txt` 파일의 그룹을 `developers`로 변경하는 명령어는?',
    answer: 'chgrp developers shared.txt',
    explanation: '`chgrp`(change group)은 파일의 소속 그룹을 변경합니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'EASY',
    title: '모든 권한 부여',
    text: '`script.sh` 파일에 모든 사용자에게 읽기, 쓰기, 실행 권한을 부여하는 명령어는?',
    answer: 'chmod 777 script.sh',
    explanation: '`777`은 소유자(7=rwx), 그룹(7=rwx), 기타(7=rwx) 모두에게 전체 권한을 부여합니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'EASY',
    title: '소유자에게만 실행 권한',
    text: '`run.sh` 파일의 소유자에게만 실행 권한을 추가하는 명령어는?',
    answer: 'chmod u+x run.sh',
    explanation: '`u+x`에서 `u`는 소유자(user), `+`는 추가, `x`는 실행 권한을 의미합니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'EASY',
    title: '기본 권한 설정',
    text: '`data.txt` 파일의 권한을 소유자만 읽기/쓰기 가능하도록 설정하는 명령어는?',
    answer: 'chmod 600 data.txt',
    explanation:
      '`600`은 소유자에게 읽기/쓰기(6=rw-) 권한만 부여하고, 그룹과 기타 사용자는 접근할 수 없습니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'EASY',
    title: '소유자와 그룹 동시 변경',
    text: '`project/` 디렉토리의 소유자를 `deploy`, 그룹을 `web`으로 동시에 변경하는 명령어는?',
    answer: 'chown deploy:web project/',
    explanation:
      '`chown user:group`은 소유자와 그룹을 동시에 변경합니다. 콜론(`:`)으로 구분합니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'EASY',
    title: '읽기 전용 설정',
    text: '`secret.key` 파일을 소유자만 읽기 가능하도록 설정하는 명령어는?',
    answer: 'chmod 400 secret.key',
    explanation:
      '`400`은 소유자에게 읽기(4=r--) 권한만 부여합니다. SSH 키 파일 등 민감한 파일에 주로 사용됩니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  // --- NORMAL (11) ---
  {
    difficulty: 'NORMAL',
    title: '재귀적 권한 변경',
    text: '`webroot/` 디렉토리와 하위 모든 파일의 권한을 755로 변경하는 명령어는?',
    answer: 'chmod -R 755 webroot/',
    explanation:
      '`chmod -R`(recursive)은 디렉토리와 하위 모든 파일에 재귀적으로 권한을 적용합니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'NORMAL',
    title: '재귀적 소유자 변경',
    text: '`/var/www/` 디렉토리와 하위 모든 파일의 소유자를 `www-data`로 변경하는 명령어는?',
    answer: 'chown -R www-data /var/www/',
    explanation: '`chown -R`은 디렉토리 하위의 모든 파일과 폴더의 소유자를 재귀적으로 변경합니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'NORMAL',
    title: 'umask 확인',
    text: '현재 설정된 기본 권한 마스크(umask) 값을 확인하는 명령어는?',
    answer: 'umask',
    explanation:
      '`umask`는 새로 생성되는 파일과 디렉토리의 기본 권한에서 제거할 권한을 정의합니다. 보통 `022`로 설정됩니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'NORMAL',
    title: 'umask 설정',
    text: '새로 생성되는 파일이 소유자만 읽기/쓰기 가능하도록 umask를 설정하는 명령어는?',
    answer: 'umask 077',
    explanation:
      '`umask 077`은 그룹과 기타 사용자의 모든 권한을 제거합니다. 새 파일은 600, 새 디렉토리는 700 권한으로 생성됩니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'NORMAL',
    title: '그룹에 쓰기 권한 추가',
    text: '`shared/` 디렉토리에 그룹 쓰기 권한을 추가하는 명령어는?',
    answer: 'chmod g+w shared/',
    explanation: '`g+w`에서 `g`는 그룹(group), `+`는 추가, `w`는 쓰기 권한입니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'NORMAL',
    title: '기타 사용자 권한 제거',
    text: '`private.txt` 파일에서 기타 사용자의 모든 권한을 제거하는 명령어는?',
    answer: 'chmod o-rwx private.txt',
    explanation:
      '`o-rwx`에서 `o`는 기타(others), `-rwx`는 읽기, 쓰기, 실행 권한을 모두 제거합니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'NORMAL',
    title: '파일만 권한 변경',
    text: '`project/` 하위에서 일반 파일만 찾아 권한을 644로 변경하는 명령어는?',
    answer: 'find project/ -type f -exec chmod 644 {} \\;',
    explanation: '`find -type f`로 파일만 찾고, `-exec chmod 644`로 각 파일에 권한을 적용합니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'NORMAL',
    title: '디렉토리만 권한 변경',
    text: '`project/` 하위에서 디렉토리만 찾아 권한을 755로 변경하는 명령어는?',
    answer: 'find project/ -type d -exec chmod 755 {} \\;',
    explanation:
      '`find -type d`로 디렉토리만 찾고, `-exec chmod 755`로 각 디렉토리에 권한을 적용합니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'NORMAL',
    title: 'SSH 키 파일 권한',
    text: 'SSH 개인 키 파일 `~/.ssh/id_rsa`에 올바른 권한을 설정하는 명령어는?',
    answer: 'chmod 600 ~/.ssh/id_rsa',
    explanation:
      'SSH 개인 키는 소유자만 읽기/쓰기 가능해야 합니다. `600` 이외의 권한이면 SSH가 키 사용을 거부합니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'NORMAL',
    title: '참조 파일 권한 복사',
    text: '`ref.txt` 파일과 동일한 권한을 `target.txt`에 적용하는 명령어는?',
    answer: 'chmod --reference=ref.txt target.txt',
    explanation: '`--reference` 옵션은 지정된 파일의 권한을 그대로 복사하여 적용합니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'NORMAL',
    title: '현재 사용자 그룹 확인',
    text: '현재 사용자가 속한 모든 그룹을 확인하는 명령어는?',
    answer: 'groups',
    explanation: '`groups`는 현재 사용자가 속한 모든 그룹을 나열합니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  // --- HARD (11) ---
  {
    difficulty: 'HARD',
    title: 'SUID 설정',
    text: '`/usr/local/bin/app` 파일에 SUID 비트를 설정하는 명령어는?',
    answer: 'chmod u+s /usr/local/bin/app',
    explanation:
      '`u+s`는 SUID(Set User ID) 비트를 설정합니다. 실행 시 파일 소유자의 권한으로 동작하게 됩니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'HARD',
    title: 'SGID 설정',
    text: '`/shared/team/` 디렉토리에 SGID 비트를 설정하는 명령어는?',
    answer: 'chmod g+s /shared/team/',
    explanation:
      '`g+s`는 SGID(Set Group ID) 비트를 설정합니다. 디렉토리에 적용하면 하위 생성 파일이 디렉토리의 그룹을 상속합니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'HARD',
    title: 'Sticky Bit 설정',
    text: '`/tmp/shared/` 디렉토리에 sticky bit를 설정하는 명령어는?',
    answer: 'chmod +t /tmp/shared/',
    explanation:
      '`+t`는 sticky bit를 설정합니다. 디렉토리에 적용하면 파일 소유자만 자신의 파일을 삭제할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'HARD',
    title: '숫자 모드 특수 권한',
    text: '`/shared/` 디렉토리에 SGID + 소유자rwx + 그룹rwx + 기타rx 권한을 숫자 모드로 설정하는 명령어는?',
    answer: 'chmod 2775 /shared/',
    explanation:
      '4자리 숫자에서 첫 자리가 특수 권한입니다. SUID=4, SGID=2, Sticky=1. `2775`는 SGID(2) + 775 권한입니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'HARD',
    title: 'SUID 파일 검색',
    text: '시스템에서 SUID 비트가 설정된 모든 파일을 찾는 명령어는?',
    answer: 'find / -perm -4000',
    explanation:
      '`-perm -4000`은 SUID 비트(4000)가 설정된 파일을 검색합니다. 보안 감사 시 중요한 점검 항목입니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'HARD',
    title: 'ACL 설정',
    text: '`project/` 디렉토리에 사용자 `bob`에게 읽기/쓰기 권한을 ACL로 추가하는 명령어는?',
    answer: 'setfacl -m u:bob:rw project/',
    explanation:
      '`setfacl -m u:bob:rw`는 기존 Unix 권한 외에 추가적인 ACL(Access Control List) 엔트리를 설정합니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'HARD',
    title: 'ACL 확인',
    text: '`project/` 디렉토리에 설정된 ACL을 확인하는 명령어는?',
    answer: 'getfacl project/',
    explanation:
      '`getfacl`은 파일이나 디렉토리에 설정된 ACL 엔트리를 표시합니다. 기본 Unix 권한과 추가 ACL을 모두 보여줍니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'HARD',
    title: '기본 ACL 설정',
    text: '`shared/` 디렉토리에 새로 생성되는 파일이 자동으로 그룹 `dev`에 읽기 권한을 갖도록 기본 ACL을 설정하는 명령어는?',
    answer: 'setfacl -d -m g:dev:r shared/',
    explanation:
      '`-d`는 기본(default) ACL을 설정합니다. 해당 디렉토리에 새로 생성되는 파일과 하위 디렉토리에 자동으로 적용됩니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'HARD',
    title: 'immutable 속성 설정',
    text: '`critical.conf` 파일을 root도 수정/삭제할 수 없도록 immutable 속성을 설정하는 명령어는?',
    answer: 'chattr +i critical.conf',
    explanation:
      '`chattr +i`는 immutable 속성을 설정합니다. 이 속성이 설정된 파일은 root라도 삭제, 수정, 이름 변경이 불가능합니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'HARD',
    title: '파일 속성 확인',
    text: '`critical.conf` 파일에 설정된 특수 속성(immutable 등)을 확인하는 명령어는?',
    answer: 'lsattr critical.conf',
    explanation:
      '`lsattr`은 파일의 특수 속성을 표시합니다. `i`는 immutable, `a`는 append-only 등을 나타냅니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  {
    difficulty: 'HARD',
    title: 'ACL 제거',
    text: '`project/` 디렉토리의 모든 ACL 엔트리를 제거하는 명령어는?',
    answer: 'setfacl -b project/',
    explanation: '`setfacl -b`는 모든 확장 ACL 엔트리를 제거하고 기본 Unix 권한만 남깁니다.',
    categoryId: 2,
    subCategoryId: 13,
  },
  // =============================================
  // Linux > Process (categoryId: 2, subCategoryId: 14)
  // =============================================
  // --- EASY (11) ---
  {
    difficulty: 'EASY',
    title: '프로세스 목록 확인',
    text: '현재 실행 중인 모든 프로세스를 사용자, PID, CPU, 메모리 등과 함께 확인하는 명령어는?',
    answer: 'ps aux',
    explanation:
      '`ps aux`에서 `a`는 모든 사용자, `u`는 상세 형식, `x`는 터미널 없는 프로세스도 포함합니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'EASY',
    title: '실시간 프로세스 모니터링',
    text: '실시간으로 프로세스 목록과 시스템 자원 사용량을 확인하는 명령어는?',
    answer: 'top',
    explanation: '`top`은 CPU, 메모리 사용량과 프로세스 목록을 실시간으로 업데이트하며 보여줍니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'EASY',
    title: '프로세스 종료',
    text: 'PID가 1234인 프로세스를 종료하는 명령어는?',
    answer: 'kill 1234',
    explanation:
      '`kill`은 지정된 PID의 프로세스에 시그널을 보냅니다. 기본 시그널은 SIGTERM(15)으로, 프로세스에 정상 종료를 요청합니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'EASY',
    title: '강제 종료',
    text: 'PID가 5678인 프로세스를 강제로 종료하는 명령어는?',
    answer: 'kill -9 5678',
    explanation:
      '`kill -9`는 SIGKILL 시그널을 보내 프로세스를 강제 종료합니다. 프로세스가 무시할 수 없는 시그널입니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'EASY',
    title: '이름으로 프로세스 종료',
    text: '이름이 "nginx"인 모든 프로세스를 종료하는 명령어는?',
    answer: 'killall nginx',
    explanation: '`killall`은 프로세스 이름으로 해당하는 모든 프로세스에 시그널을 보냅니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'EASY',
    title: '백그라운드 작업 확인',
    text: '현재 쉘의 백그라운드 작업 목록을 확인하는 명령어는?',
    answer: 'jobs',
    explanation: '`jobs`는 현재 쉘 세션에서 실행 중인 백그라운드 및 중단된 작업 목록을 표시합니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'EASY',
    title: '포그라운드로 전환',
    text: '가장 최근 백그라운드 작업을 포그라운드로 가져오는 명령어는?',
    answer: 'fg',
    explanation:
      '`fg`는 백그라운드 작업을 포그라운드로 전환합니다. 인자 없이 실행하면 가장 최근 작업이 선택됩니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'EASY',
    title: '현재 PID 확인',
    text: '현재 쉘의 PID를 확인하는 명령어는?',
    answer: 'echo $$',
    explanation: '`$$`는 현재 쉘 프로세스의 PID를 저장하는 특수 변수입니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'EASY',
    title: '시스템 가동 시간',
    text: '시스템의 가동 시간과 부하 평균을 확인하는 명령어는?',
    answer: 'uptime',
    explanation:
      '`uptime`은 현재 시간, 시스템 가동 시간, 접속 사용자 수, 1/5/15분 부하 평균을 표시합니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'EASY',
    title: '프로세스 일시 중단',
    text: '포그라운드에서 실행 중인 프로세스를 일시 중단하는 키보드 단축키는?',
    answer: 'Ctrl+Z',
    explanation:
      '`Ctrl+Z`는 포그라운드 프로세스에 SIGTSTP 시그널을 보내 일시 중단합니다. `bg`로 백그라운드 실행을 재개할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'EASY',
    title: '백그라운드 재개',
    text: '중단된 작업을 백그라운드에서 재개하는 명령어는?',
    answer: 'bg',
    explanation: '`bg`는 중단된(stopped) 작업을 백그라운드에서 실행 재개합니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  // --- NORMAL (11) ---
  {
    difficulty: 'NORMAL',
    title: 'htop 사용',
    text: '`top`보다 개선된 인터랙티브 프로세스 뷰어를 실행하는 명령어는?',
    answer: 'htop',
    explanation:
      '`htop`은 `top`의 개선 버전으로, 컬러 출력, 마우스 지원, 프로세스 트리 뷰 등 향상된 인터페이스를 제공합니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'NORMAL',
    title: '프로세스 트리 보기',
    text: '프로세스를 부모-자식 관계의 트리 형태로 보는 명령어는?',
    answer: 'pstree',
    explanation:
      '`pstree`는 프로세스를 계층적 트리 구조로 표시하여 부모-자식 관계를 시각적으로 보여줍니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'NORMAL',
    title: '특정 프로세스 검색',
    text: '"node" 프로세스의 PID를 찾는 명령어는?',
    answer: 'pgrep node',
    explanation: '`pgrep`은 프로세스 이름 패턴으로 검색하여 일치하는 PID를 출력합니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'NORMAL',
    title: 'nohup 실행',
    text: '`./server.sh`를 로그아웃 후에도 계속 실행되도록 하는 명령어는?',
    answer: 'nohup ./server.sh &',
    explanation:
      '`nohup`은 HUP 시그널을 무시하여 터미널 세션 종료 후에도 프로세스가 계속 실행됩니다. 출력은 `nohup.out`에 저장됩니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'NORMAL',
    title: '프로세스 우선순위 변경',
    text: 'PID 1234 프로세스의 nice 값을 10으로 변경하는 명령어는?',
    answer: 'renice 10 -p 1234',
    explanation:
      '`renice`는 실행 중인 프로세스의 우선순위(nice 값)를 변경합니다. 값이 높을수록 우선순위가 낮아집니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'NORMAL',
    title: '낮은 우선순위로 실행',
    text: '`make build`를 낮은 우선순위(nice 값 19)로 실행하는 명령어는?',
    answer: 'nice -n 19 make build',
    explanation:
      '`nice -n 19`는 가장 낮은 우선순위로 프로세스를 시작합니다. 시스템 부하를 최소화하며 백그라운드 작업에 적합합니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'NORMAL',
    title: '특정 포트 사용 프로세스',
    text: '8080 포트를 사용하고 있는 프로세스를 확인하는 명령어는?',
    answer: 'lsof -i :8080',
    explanation: '`lsof -i :8080`은 8080 포트를 사용하는 프로세스의 상세 정보를 보여줍니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'NORMAL',
    title: '메모리 사용량 확인',
    text: '시스템의 물리 메모리와 스왑 사용량을 사람이 읽기 쉬운 형태로 확인하는 명령어는?',
    answer: 'free -h',
    explanation: '`free -h`는 메모리 사용량을 KB/MB/GB 등 사람이 읽기 쉬운 단위로 표시합니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'NORMAL',
    title: '프로세스 시그널 목록',
    text: '사용 가능한 모든 시그널 목록을 확인하는 명령어는?',
    answer: 'kill -l',
    explanation: '`kill -l`은 시스템에서 지원하는 모든 시그널의 번호와 이름을 나열합니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'NORMAL',
    title: '프로세스 상세 검색',
    text: '"java"를 포함하는 프로세스의 PID와 전체 명령어를 함께 출력하는 명령어는?',
    answer: 'pgrep -a java',
    explanation: '`pgrep -a`는 일치하는 프로세스의 PID와 함께 전체 실행 명령어를 표시합니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'NORMAL',
    title: '특정 사용자 프로세스',
    text: '`www-data` 사용자가 실행한 프로세스만 확인하는 명령어는?',
    answer: 'ps -u www-data',
    explanation: '`ps -u www-data`는 지정된 사용자가 실행한 프로세스만 필터링하여 표시합니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  // --- HARD (11) ---
  {
    difficulty: 'HARD',
    title: 'strace 추적',
    text: 'PID 1234 프로세스의 시스템 콜을 실시간으로 추적하는 명령어는?',
    answer: 'strace -p 1234',
    explanation:
      '`strace -p`는 실행 중인 프로세스에 연결하여 시스템 콜과 시그널을 실시간으로 추적합니다. 디버깅에 필수적인 도구입니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'HARD',
    title: 'cgroups 메모리 제한',
    text: '`mygroup` cgroup에 최대 메모리를 512MB로 제한하는 명령어는?',
    answer: 'cgset -r memory.limit_in_bytes=536870912 mygroup',
    explanation:
      '`cgset`은 cgroup의 리소스 제한을 설정합니다. `memory.limit_in_bytes`로 메모리 상한을 바이트 단위로 지정합니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'HARD',
    title: '/proc 정보 확인',
    text: 'PID 1234 프로세스의 메모리 맵 정보를 확인하는 파일 경로는?',
    answer: '/proc/1234/maps',
    explanation:
      '`/proc/<pid>/maps`는 프로세스의 가상 메모리 영역 매핑 정보를 담고 있습니다. 각 영역의 주소, 권한, 매핑 파일 등을 확인할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'HARD',
    title: '좀비 프로세스 찾기',
    text: '시스템에서 좀비(zombie) 상태의 프로세스를 찾는 명령어는?',
    answer: 'ps aux | grep Z',
    explanation:
      '좀비 프로세스는 `STAT` 열에 `Z`로 표시됩니다. 부모 프로세스가 종료 상태를 수거하지 않은 자식 프로세스입니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'HARD',
    title: 'OOM 점수 확인',
    text: 'PID 1234 프로세스의 OOM killer 점수를 확인하는 명령어는?',
    answer: 'cat /proc/1234/oom_score',
    explanation:
      '`/proc/<pid>/oom_score`는 메모리 부족 시 커널이 종료할 프로세스를 선택하는 점수입니다. 값이 높을수록 종료될 가능성이 높습니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'HARD',
    title: 'CPU 코어별 사용률',
    text: '각 CPU 코어별 사용률을 1초 간격으로 확인하는 명령어는?',
    answer: 'mpstat -P ALL 1',
    explanation:
      '`mpstat -P ALL 1`은 모든 CPU 코어의 사용률을 1초 간격으로 표시합니다. 특정 코어에 부하가 집중되는지 확인할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'HARD',
    title: 'timeout 실행',
    text: '`wget` 명령을 최대 30초까지만 실행하고 초과 시 강제 종료하는 명령어는?',
    answer: 'timeout 30 wget http://example.com/file.zip',
    explanation:
      '`timeout`은 지정된 시간이 경과하면 프로세스를 자동으로 종료합니다. 행(hang) 방지에 유용합니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'HARD',
    title: '프로세스 파일 디스크립터',
    text: 'PID 1234 프로세스가 열고 있는 모든 파일을 확인하는 명령어는?',
    answer: 'lsof -p 1234',
    explanation:
      '`lsof -p`는 지정된 프로세스가 열고 있는 모든 파일(일반 파일, 소켓, 파이프 등)을 표시합니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'HARD',
    title: 'systemd 서비스 상태',
    text: '`nginx` 서비스의 상태와 최근 로그를 확인하는 명령어는?',
    answer: 'systemctl status nginx',
    explanation:
      '`systemctl status`는 서비스의 활성 상태, PID, 메모리 사용량, 최근 로그 출력을 보여줍니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'HARD',
    title: 'watch로 반복 모니터링',
    text: '`df -h` 명령을 5초마다 반복 실행하여 디스크 사용량을 모니터링하는 명령어는?',
    answer: 'watch -n 5 df -h',
    explanation:
      '`watch -n 5`는 지정된 명령을 5초 간격으로 반복 실행하고 결과를 화면에 갱신합니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  {
    difficulty: 'HARD',
    title: 'ionice 설정',
    text: '`rsync` 명령을 가장 낮은 I/O 우선순위(idle)로 실행하는 명령어는?',
    answer: 'ionice -c 3 rsync -av src/ dest/',
    explanation:
      '`ionice -c 3`은 idle 클래스로 I/O 우선순위를 설정합니다. 다른 프로세스의 I/O가 없을 때만 디스크를 사용합니다.',
    categoryId: 2,
    subCategoryId: 14,
  },
  // =============================================
  // Linux > Network (categoryId: 2, subCategoryId: 15)
  // =============================================
  // --- EASY (11) ---
  {
    difficulty: 'EASY',
    title: 'IP 주소 확인',
    text: '현재 시스템의 네트워크 인터페이스와 IP 주소를 확인하는 명령어는?',
    answer: 'ip addr',
    explanation:
      '`ip addr`(또는 `ip a`)은 모든 네트워크 인터페이스의 IP 주소, MAC 주소, 상태 등을 표시합니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'EASY',
    title: '네트워크 연결 확인',
    text: '`google.com` 서버에 네트워크 연결이 가능한지 확인하는 명령어는?',
    answer: 'ping google.com',
    explanation: '`ping`은 ICMP 패킷을 보내 대상 호스트의 응답 여부와 지연 시간을 확인합니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'EASY',
    title: '호스트 이름 확인',
    text: '현재 시스템의 호스트 이름을 확인하는 명령어는?',
    answer: 'hostname',
    explanation: '`hostname`은 현재 시스템에 설정된 호스트 이름을 출력합니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'EASY',
    title: 'DNS 조회',
    text: '`example.com` 도메인의 IP 주소를 조회하는 명령어는?',
    answer: 'nslookup example.com',
    explanation: '`nslookup`은 DNS 서버에 질의하여 도메인 이름에 대응하는 IP 주소를 조회합니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'EASY',
    title: '파일 다운로드',
    text: '`https://example.com/file.zip` 파일을 다운로드하는 명령어는?',
    answer: 'wget https://example.com/file.zip',
    explanation: '`wget`은 URL에서 파일을 다운로드합니다. 현재 디렉토리에 파일이 저장됩니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'EASY',
    title: '열린 포트 확인',
    text: '현재 시스템에서 열려있는 TCP 포트와 연결 상태를 확인하는 명령어는?',
    answer: 'ss -tuln',
    explanation:
      '`ss -tuln`에서 `-t`는 TCP, `-u`는 UDP, `-l`은 리스닝, `-n`은 숫자 표시입니다. 열린 포트를 빠르게 확인할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'EASY',
    title: 'curl로 요청 보내기',
    text: '`https://api.example.com/health` URL에 GET 요청을 보내는 명령어는?',
    answer: 'curl https://api.example.com/health',
    explanation: '`curl`은 URL로 HTTP 요청을 보내고 응답을 출력합니다. 기본 메서드는 GET입니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'EASY',
    title: '라우팅 테이블 확인',
    text: '현재 시스템의 라우팅 테이블을 확인하는 명령어는?',
    answer: 'ip route',
    explanation:
      '`ip route`는 커널 라우팅 테이블을 표시합니다. 기본 게이트웨이와 네트워크 경로를 확인할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'EASY',
    title: 'ping 횟수 제한',
    text: '`8.8.8.8`에 4번만 ping을 보내는 명령어는?',
    answer: 'ping -c 4 8.8.8.8',
    explanation:
      '`-c 4`는 ICMP 패킷을 4번만 보내고 종료합니다. 옵션 없이 실행하면 수동으로 중단할 때까지 계속 보냅니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'EASY',
    title: 'DNS 설정 확인',
    text: '시스템에 설정된 DNS 서버 주소를 확인하는 파일 경로는?',
    answer: 'cat /etc/resolv.conf',
    explanation:
      '`/etc/resolv.conf` 파일에 시스템이 사용하는 DNS 서버 주소가 `nameserver` 항목으로 설정되어 있습니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'EASY',
    title: 'hosts 파일 확인',
    text: '로컬 호스트 이름 매핑 설정을 확인하는 파일 경로는?',
    answer: 'cat /etc/hosts',
    explanation: '`/etc/hosts` 파일은 DNS 조회 전에 참조되는 로컬 호스트 이름-IP 매핑 파일입니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  // --- NORMAL (11) ---
  {
    difficulty: 'NORMAL',
    title: '경로 추적',
    text: '`google.com`까지의 네트워크 경로(라우팅 홉)를 추적하는 명령어는?',
    answer: 'traceroute google.com',
    explanation:
      '`traceroute`는 패킷이 목적지까지 도달하는 경로의 각 라우터(홉)와 지연 시간을 표시합니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'NORMAL',
    title: 'curl POST 요청',
    text: '`https://api.example.com/data`에 JSON 데이터 `{"name":"test"}`를 POST로 전송하는 명령어는?',
    answer:
      'curl -X POST -H \'Content-Type: application/json\' -d \'{"name":"test"}\' https://api.example.com/data',
    explanation: '`-X POST`는 메서드 지정, `-H`는 헤더, `-d`는 요청 본문을 설정합니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'NORMAL',
    title: 'dig DNS 조회',
    text: '`example.com`의 A 레코드를 `dig` 명령어로 조회하는 명령어는?',
    answer: 'dig example.com A',
    explanation:
      '`dig`은 DNS 질의 도구로, A 레코드(IPv4), AAAA(IPv6), MX(메일), NS(네임서버) 등 다양한 레코드 타입을 조회할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'NORMAL',
    title: '포트 스캔',
    text: '`192.168.1.1` 서버의 열린 포트를 스캔하는 명령어는?',
    answer: 'nmap 192.168.1.1',
    explanation:
      '`nmap`은 네트워크 탐색 및 포트 스캔 도구입니다. 대상 호스트의 열린 포트와 서비스를 탐지합니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'NORMAL',
    title: 'wget 출력 파일 지정',
    text: '`https://example.com/data.json` 파일을 `output.json`으로 저장하는 명령어는?',
    answer: 'wget -O output.json https://example.com/data.json',
    explanation: '`-O`는 다운로드할 파일의 저장 이름을 지정합니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'NORMAL',
    title: '네트워크 인터페이스 활성화',
    text: '`eth0` 네트워크 인터페이스를 활성화하는 명령어는?',
    answer: 'ip link set eth0 up',
    explanation:
      '`ip link set <interface> up`은 네트워크 인터페이스를 활성화합니다. `down`은 비활성화합니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'NORMAL',
    title: 'netcat 포트 리스닝',
    text: 'TCP 8080 포트에서 연결을 대기하는 명령어는?',
    answer: 'nc -l 8080',
    explanation:
      '`nc -l 8080`은 8080 포트에서 들어오는 TCP 연결을 대기합니다. 간단한 서버 테스트에 유용합니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'NORMAL',
    title: 'curl 응답 헤더 확인',
    text: '`https://example.com`의 HTTP 응답 헤더만 확인하는 명령어는?',
    answer: 'curl -I https://example.com',
    explanation: '`curl -I`(또는 `--head`)는 HEAD 요청을 보내 응답 헤더만 표시합니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'NORMAL',
    title: 'ARP 테이블 확인',
    text: '현재 시스템의 ARP 캐시 테이블을 확인하는 명령어는?',
    answer: 'ip neigh',
    explanation:
      '`ip neigh`(neighbor)는 ARP 캐시를 표시합니다. 같은 네트워크의 장치 MAC 주소를 확인할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'NORMAL',
    title: '네트워크 통계',
    text: '네트워크 인터페이스별 송수신 패킷 통계를 확인하는 명령어는?',
    answer: 'ip -s link',
    explanation:
      '`ip -s link`는 각 인터페이스의 송수신 바이트, 패킷 수, 에러, 드롭 등 통계를 표시합니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'NORMAL',
    title: 'SCP 파일 전송',
    text: '로컬의 `backup.tar.gz`를 원격 서버 `user@server:/tmp/`로 전송하는 명령어는?',
    answer: 'scp backup.tar.gz user@server:/tmp/',
    explanation: '`scp`는 SSH 프로토콜을 통해 로컬과 원격 서버 간에 파일을 안전하게 전송합니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  // --- HARD (11) ---
  {
    difficulty: 'HARD',
    title: 'iptables 포트 허용',
    text: 'TCP 80 포트의 인바운드 트래픽을 허용하는 iptables 규칙을 추가하는 명령어는?',
    answer: 'iptables -A INPUT -p tcp --dport 80 -j ACCEPT',
    explanation:
      '`-A INPUT`은 인바운드 규칙 추가, `-p tcp`는 프로토콜, `--dport 80`은 대상 포트, `-j ACCEPT`는 허용 정책입니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'HARD',
    title: 'iptables 규칙 확인',
    text: '현재 설정된 모든 iptables 방화벽 규칙을 줄 번호와 함께 확인하는 명령어는?',
    answer: 'iptables -L -n --line-numbers',
    explanation: '`-L`은 목록, `-n`은 숫자 형식, `--line-numbers`는 규칙 번호를 표시합니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'HARD',
    title: 'tcpdump 패킷 캡처',
    text: '`eth0` 인터페이스에서 80 포트의 TCP 패킷을 캡처하는 명령어는?',
    answer: 'tcpdump -i eth0 tcp port 80',
    explanation:
      '`tcpdump`는 네트워크 패킷을 캡처합니다. `-i`는 인터페이스, `tcp port 80`은 필터 조건입니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'HARD',
    title: 'IP 주소 추가',
    text: '`eth0` 인터페이스에 IP 주소 `192.168.1.100/24`를 추가하는 명령어는?',
    answer: 'ip addr add 192.168.1.100/24 dev eth0',
    explanation:
      '`ip addr add`는 인터페이스에 IP 주소를 추가합니다. 하나의 인터페이스에 여러 IP를 할당할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'HARD',
    title: 'SSH 터널링',
    text: '로컬 8080 포트를 원격 서버의 3306 포트로 SSH 터널링하는 명령어는?',
    answer: 'ssh -L 8080:localhost:3306 user@server',
    explanation:
      '`-L 8080:localhost:3306`은 로컬 8080 포트를 원격 서버의 3306 포트로 포워딩합니다. 로컬에서 8080으로 접속하면 원격 3306에 연결됩니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'HARD',
    title: '네트워크 네임스페이스',
    text: '`test_ns`라는 네트워크 네임스페이스를 생성하는 명령어는?',
    answer: 'ip netns add test_ns',
    explanation:
      '`ip netns add`는 격리된 네트워크 네임스페이스를 생성합니다. 컨테이너 기술의 기반이 되는 기능입니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'HARD',
    title: 'tcpdump 파일 저장',
    text: '`eth0`의 모든 패킷을 `capture.pcap` 파일로 저장하는 명령어는?',
    answer: 'tcpdump -i eth0 -w capture.pcap',
    explanation:
      '`-w`는 캡처한 패킷을 pcap 형식으로 파일에 저장합니다. Wireshark 등에서 분석할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'HARD',
    title: '정적 라우트 추가',
    text: '`10.0.0.0/8` 네트워크로 향하는 트래픽을 게이트웨이 `192.168.1.1`로 라우팅하는 규칙을 추가하는 명령어는?',
    answer: 'ip route add 10.0.0.0/8 via 192.168.1.1',
    explanation:
      '`ip route add`는 커널 라우팅 테이블에 정적 라우트를 추가합니다. `via`는 게이트웨이를 지정합니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'HARD',
    title: 'curl 인증서 무시',
    text: 'SSL 인증서 검증을 무시하고 HTTPS 요청을 보내는 curl 명령어는?',
    answer: 'curl -k https://self-signed.example.com',
    explanation:
      '`-k`(또는 `--insecure`)는 SSL 인증서 검증을 건너뜁니다. 자체 서명 인증서를 사용하는 개발 환경에서 사용합니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'HARD',
    title: 'iptables NAT 설정',
    text: '소스 NAT를 설정하여 내부 네트워크(`10.0.0.0/24`)의 트래픽을 `eth0`으로 마스커레이드하는 명령어는?',
    answer: 'iptables -t nat -A POSTROUTING -s 10.0.0.0/24 -o eth0 -j MASQUERADE',
    explanation:
      '`-t nat`은 NAT 테이블, `POSTROUTING`은 나가는 패킷에 적용, `MASQUERADE`는 자동 소스 주소 변환입니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  {
    difficulty: 'HARD',
    title: 'nftables 규칙 확인',
    text: '현재 설정된 nftables 방화벽 규칙셋을 확인하는 명령어는?',
    answer: 'nft list ruleset',
    explanation:
      '`nft list ruleset`은 nftables의 모든 테이블과 체인, 규칙을 표시합니다. iptables의 차세대 대체 도구입니다.',
    categoryId: 2,
    subCategoryId: 15,
  },
  // =============================================
  // Linux > System (categoryId: 2, subCategoryId: 16)
  // =============================================
  // --- EASY (11) ---
  {
    difficulty: 'EASY',
    title: '시스템 재부팅',
    text: '시스템을 즉시 재부팅하는 명령어는?',
    answer: 'reboot',
    explanation: '`reboot`은 시스템을 즉시 재시작합니다. root 권한이 필요합니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'EASY',
    title: '시스템 종료',
    text: '시스템을 즉시 종료(셧다운)하는 명령어는?',
    answer: 'shutdown -h now',
    explanation: '`shutdown -h now`에서 `-h`는 halt(종료), `now`는 즉시 실행을 의미합니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'EASY',
    title: '커널 버전 확인',
    text: '현재 실행 중인 리눅스 커널 버전을 확인하는 명령어는?',
    answer: 'uname -r',
    explanation: '`uname -r`은 현재 커널의 릴리스 버전을 출력합니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'EASY',
    title: '시스템 정보 확인',
    text: '커널 이름, 버전, 아키텍처 등 전체 시스템 정보를 확인하는 명령어는?',
    answer: 'uname -a',
    explanation:
      '`uname -a`는 커널 이름, 호스트명, 커널 릴리스, 버전, 아키텍처 등 모든 시스템 정보를 출력합니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'EASY',
    title: '현재 날짜 확인',
    text: '현재 날짜와 시간을 확인하는 명령어는?',
    answer: 'date',
    explanation: '`date`는 현재 시스템의 날짜와 시간을 표시합니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'EASY',
    title: '시스템 가동 시간',
    text: '시스템이 마지막 부팅 이후 얼마나 실행 중인지 확인하는 명령어는?',
    answer: 'uptime',
    explanation: '`uptime`은 현재 시간, 가동 시간, 접속 사용자 수, 로드 평균을 출력합니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'EASY',
    title: 'OS 정보 확인',
    text: '현재 설치된 리눅스 배포판의 이름과 버전을 확인하는 명령어는?',
    answer: 'cat /etc/os-release',
    explanation: '`/etc/os-release` 파일에는 배포판 이름, 버전, ID 등의 정보가 포함되어 있습니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'EASY',
    title: '서비스 시작',
    text: '`nginx` 서비스를 시작하는 systemctl 명령어는?',
    answer: 'systemctl start nginx',
    explanation: '`systemctl start`는 지정된 서비스를 즉시 시작합니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'EASY',
    title: '서비스 중지',
    text: '`nginx` 서비스를 중지하는 명령어는?',
    answer: 'systemctl stop nginx',
    explanation: '`systemctl stop`은 실행 중인 서비스를 중지합니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'EASY',
    title: '서비스 재시작',
    text: '`nginx` 서비스를 재시작하는 명령어는?',
    answer: 'systemctl restart nginx',
    explanation:
      '`systemctl restart`는 서비스를 중지한 후 다시 시작합니다. 설정 변경 후 적용할 때 사용합니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'EASY',
    title: '서비스 자동 시작 설정',
    text: '`nginx` 서비스가 부팅 시 자동으로 시작되도록 설정하는 명령어는?',
    answer: 'systemctl enable nginx',
    explanation: '`systemctl enable`은 서비스를 부팅 시 자동 시작하도록 등록합니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  // --- NORMAL (11) ---
  {
    difficulty: 'NORMAL',
    title: '서비스 상태 확인',
    text: '`nginx` 서비스의 실행 상태와 최근 로그를 확인하는 명령어는?',
    answer: 'systemctl status nginx',
    explanation:
      '`systemctl status`는 서비스의 활성 상태, PID, 메모리 사용량, 최근 journal 로그를 표시합니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'NORMAL',
    title: '모든 서비스 목록',
    text: '시스템에 등록된 모든 서비스의 상태를 확인하는 명령어는?',
    answer: 'systemctl list-units --type=service',
    explanation: '`list-units --type=service`는 로드된 모든 서비스 유닛의 상태를 나열합니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'NORMAL',
    title: '시스템 로그 확인',
    text: '시스템 journal 로그의 최근 50줄을 확인하는 명령어는?',
    answer: 'journalctl -n 50',
    explanation: '`journalctl -n 50`은 systemd 저널에서 최근 50개의 로그 엔트리를 표시합니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'NORMAL',
    title: '특정 서비스 로그',
    text: '`nginx` 서비스의 로그만 확인하는 명령어는?',
    answer: 'journalctl -u nginx',
    explanation: '`journalctl -u`는 지정된 systemd 유닛(서비스)의 로그만 필터링합니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'NORMAL',
    title: '실시간 로그 추적',
    text: 'systemd 저널 로그를 실시간으로 추적하는 명령어는?',
    answer: 'journalctl -f',
    explanation: '`journalctl -f`는 `tail -f`와 유사하게 새로운 로그를 실시간으로 출력합니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'NORMAL',
    title: '예약 종료',
    text: '10분 후에 시스템을 종료하는 명령어는?',
    answer: 'shutdown -h +10',
    explanation:
      '`shutdown -h +10`은 10분 후 시스템 종료를 예약합니다. 접속 중인 사용자에게 경고 메시지를 보냅니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'NORMAL',
    title: '타임존 설정',
    text: '시스템 타임존을 "Asia/Seoul"로 설정하는 명령어는?',
    answer: 'timedatectl set-timezone Asia/Seoul',
    explanation: '`timedatectl set-timezone`은 시스템의 타임존을 변경합니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'NORMAL',
    title: '서비스 자동시작 해제',
    text: '`nginx` 서비스의 부팅 시 자동 시작을 해제하는 명령어는?',
    answer: 'systemctl disable nginx',
    explanation:
      '`systemctl disable`은 서비스의 부팅 시 자동 시작 설정을 해제합니다. 현재 실행 중인 서비스에는 영향이 없습니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'NORMAL',
    title: '환경변수 영구 설정',
    text: '모든 사용자에게 적용되는 환경변수를 영구 설정하기 위해 수정해야 하는 파일은?',
    answer: '/etc/environment',
    explanation:
      '`/etc/environment`는 시스템 전역 환경변수를 설정하는 파일입니다. 모든 사용자와 서비스에 적용됩니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'NORMAL',
    title: '서비스 리로드',
    text: '`nginx` 서비스를 중단 없이 설정만 다시 로드하는 명령어는?',
    answer: 'systemctl reload nginx',
    explanation:
      '`systemctl reload`는 서비스를 중단하지 않고 설정 파일만 다시 로드합니다. 무중단 설정 적용에 유용합니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'NORMAL',
    title: '부팅 시간 분석',
    text: '시스템 부팅에 소요된 시간을 분석하는 명령어는?',
    answer: 'systemd-analyze',
    explanation: '`systemd-analyze`는 커널, initrd, 사용자 공간의 부팅 소요 시간을 표시합니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  // --- HARD (11) ---
  {
    difficulty: 'HARD',
    title: '커널 파라미터 확인',
    text: '현재 커널의 모든 sysctl 파라미터를 확인하는 명령어는?',
    answer: 'sysctl -a',
    explanation:
      '`sysctl -a`는 커널의 모든 런타임 파라미터를 표시합니다. 네트워크, 메모리, 파일 시스템 등의 설정을 확인할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'HARD',
    title: '커널 파라미터 변경',
    text: 'IP 포워딩을 활성화하는 sysctl 명령어는?',
    answer: 'sysctl -w net.ipv4.ip_forward=1',
    explanation:
      '`sysctl -w`는 커널 파라미터를 런타임에 변경합니다. 영구 적용은 `/etc/sysctl.conf`에 추가해야 합니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'HARD',
    title: 'systemd 유닛 파일 위치',
    text: '`nginx` 서비스의 systemd 유닛 파일 내용을 확인하는 명령어는?',
    answer: 'systemctl cat nginx',
    explanation:
      '`systemctl cat`은 서비스의 유닛 파일 전체 내용을 표시합니다. 서비스 설정을 확인할 때 유용합니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'HARD',
    title: 'systemd 타이머 목록',
    text: '시스템에 등록된 모든 systemd 타이머를 확인하는 명령어는?',
    answer: 'systemctl list-timers',
    explanation:
      '`list-timers`는 활성화된 모든 systemd 타이머와 다음 실행 시간, 마지막 실행 시간을 표시합니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'HARD',
    title: 'dmesg 로그 확인',
    text: '커널 링 버퍼의 메시지를 사람이 읽기 쉬운 시간 형식으로 확인하는 명령어는?',
    answer: 'dmesg -T',
    explanation:
      '`dmesg -T`는 커널 메시지를 사람이 읽기 쉬운 타임스탬프와 함께 출력합니다. 하드웨어 문제 진단에 유용합니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'HARD',
    title: '부팅 서비스 순서',
    text: '부팅 시 각 서비스가 시작되는 데 걸린 시간을 내림차순으로 확인하는 명령어는?',
    answer: 'systemd-analyze blame',
    explanation:
      '`systemd-analyze blame`은 각 유닛이 시작되는 데 소요된 시간을 가장 긴 것부터 내림차순으로 표시합니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'HARD',
    title: 'journalctl 날짜 필터',
    text: '오늘 발생한 시스템 로그만 확인하는 명령어는?',
    answer: 'journalctl --since today',
    explanation:
      '`--since today`는 오늘 자정 이후의 로그만 필터링합니다. `--since "2024-01-01"` 형태로 특정 날짜도 지정 가능합니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'HARD',
    title: '서비스 의존성 확인',
    text: '`nginx` 서비스의 의존성 트리를 확인하는 명령어는?',
    answer: 'systemctl list-dependencies nginx',
    explanation:
      '`list-dependencies`는 서비스의 의존성을 트리 형태로 표시합니다. 서비스 시작 순서와 관련 유닛을 파악할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'HARD',
    title: '서비스 유닛 편집',
    text: '`nginx` 서비스의 systemd 유닛 설정을 오버라이드하기 위해 드롭인 파일을 편집하는 명령어는?',
    answer: 'systemctl edit nginx',
    explanation:
      '`systemctl edit`은 서비스의 드롭인 오버라이드 파일을 생성/편집합니다. 원본 유닛 파일을 수정하지 않고 설정을 변경할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'HARD',
    title: '로드된 커널 모듈 확인',
    text: '현재 로드된 모든 커널 모듈을 확인하는 명령어는?',
    answer: 'lsmod',
    explanation: '`lsmod`는 현재 커널에 로드된 모듈과 각 모듈의 크기, 의존성을 표시합니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  {
    difficulty: 'HARD',
    title: '커널 모듈 로드',
    text: '`br_netfilter` 커널 모듈을 수동으로 로드하는 명령어는?',
    answer: 'modprobe br_netfilter',
    explanation:
      '`modprobe`는 커널 모듈을 로드합니다. 의존성이 있는 다른 모듈도 자동으로 함께 로드합니다.',
    categoryId: 2,
    subCategoryId: 16,
  },
  // =============================================
  // Linux > User (categoryId: 2, subCategoryId: 17)
  // =============================================
  // --- EASY (11) ---
  {
    difficulty: 'EASY',
    title: '현재 사용자 확인',
    text: '현재 로그인된 사용자의 이름을 확인하는 명령어는?',
    answer: 'whoami',
    explanation: '`whoami`는 현재 유효 사용자(effective user)의 이름을 출력합니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'EASY',
    title: '사용자 정보 확인',
    text: '현재 사용자의 UID, GID, 소속 그룹을 확인하는 명령어는?',
    answer: 'id',
    explanation: '`id`는 현재 사용자의 UID, GID, 소속 그룹 목록을 표시합니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'EASY',
    title: '비밀번호 변경',
    text: '현재 사용자의 비밀번호를 변경하는 명령어는?',
    answer: 'passwd',
    explanation:
      '`passwd`는 현재 사용자의 비밀번호를 변경합니다. root는 다른 사용자의 비밀번호도 변경할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'EASY',
    title: '사용자 추가',
    text: '`developer`라는 새 사용자를 생성하는 명령어는?',
    answer: 'useradd developer',
    explanation: '`useradd`는 새 사용자 계정을 생성합니다. root 권한이 필요합니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'EASY',
    title: '사용자 삭제',
    text: '`olduser` 사용자 계정을 삭제하는 명령어는?',
    answer: 'userdel olduser',
    explanation: '`userdel`은 사용자 계정을 삭제합니다. 홈 디렉토리는 기본적으로 남아있습니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'EASY',
    title: 'root 전환',
    text: 'root 사용자로 전환하는 명령어는?',
    answer: 'su -',
    explanation: '`su -`는 root 사용자로 전환하며, root의 환경변수와 홈 디렉토리를 로드합니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'EASY',
    title: 'sudo 실행',
    text: '`apt update` 명령을 root 권한으로 실행하는 명령어는?',
    answer: 'sudo apt update',
    explanation:
      '`sudo`는 일반 사용자가 root 권한으로 명령을 실행할 수 있게 합니다. `/etc/sudoers`에 등록된 사용자만 사용 가능합니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'EASY',
    title: '접속 사용자 확인',
    text: '현재 시스템에 로그인한 모든 사용자를 확인하는 명령어는?',
    answer: 'who',
    explanation: '`who`는 현재 시스템에 로그인한 사용자 이름, 터미널, 로그인 시간을 표시합니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'EASY',
    title: '그룹 추가',
    text: '`developers`라는 새 그룹을 생성하는 명령어는?',
    answer: 'groupadd developers',
    explanation: '`groupadd`는 새 그룹을 생성합니다. root 권한이 필요합니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'EASY',
    title: '사용자 목록 확인',
    text: '시스템에 등록된 모든 사용자 계정을 확인하는 파일은?',
    answer: 'cat /etc/passwd',
    explanation: '`/etc/passwd` 파일에 시스템의 모든 사용자 계정 정보가 저장되어 있습니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'EASY',
    title: '소속 그룹 확인',
    text: '`developer` 사용자가 속한 모든 그룹을 확인하는 명령어는?',
    answer: 'groups developer',
    explanation: '`groups`는 지정된 사용자가 속한 모든 그룹을 나열합니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  // --- NORMAL (11) ---
  {
    difficulty: 'NORMAL',
    title: '홈 디렉토리와 함께 사용자 생성',
    text: '`webdev` 사용자를 홈 디렉토리 자동 생성과 함께 추가하는 명령어는?',
    answer: 'useradd -m webdev',
    explanation:
      '`-m`(또는 `--create-home`) 옵션은 사용자의 홈 디렉토리(`/home/webdev`)를 자동으로 생성합니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'NORMAL',
    title: '사용자를 그룹에 추가',
    text: '`bob` 사용자를 `docker` 그룹에 추가하는 명령어는? (기존 그룹 유지)',
    answer: 'usermod -aG docker bob',
    explanation:
      '`usermod -aG`에서 `-a`는 추가(append), `-G`는 보조 그룹을 지정합니다. `-a` 없이 사용하면 기존 그룹이 제거됩니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'NORMAL',
    title: '홈 디렉토리 포함 삭제',
    text: '`olduser` 사용자를 홈 디렉토리와 메일 스풀까지 함께 삭제하는 명령어는?',
    answer: 'userdel -r olduser',
    explanation: '`userdel -r`은 사용자 계정과 함께 홈 디렉토리와 메일 스풀을 삭제합니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'NORMAL',
    title: '사용자 쉘 변경',
    text: '`developer` 사용자의 기본 쉘을 `/bin/zsh`로 변경하는 명령어는?',
    answer: 'usermod -s /bin/zsh developer',
    explanation: '`usermod -s`는 사용자의 기본 로그인 쉘을 변경합니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'NORMAL',
    title: '계정 잠금',
    text: '`user1` 사용자의 계정을 잠금(비활성화)하는 명령어는?',
    answer: 'usermod -L user1',
    explanation: '`usermod -L`(Lock)은 비밀번호 앞에 `!`를 추가하여 로그인을 차단합니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'NORMAL',
    title: '계정 잠금 해제',
    text: '잠긴 `user1` 사용자의 계정을 다시 활성화하는 명령어는?',
    answer: 'usermod -U user1',
    explanation: '`usermod -U`(Unlock)은 비밀번호 앞의 `!`를 제거하여 로그인을 다시 허용합니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'NORMAL',
    title: '다른 사용자 비밀번호 설정',
    text: 'root로서 `newuser` 사용자의 비밀번호를 설정하는 명령어는?',
    answer: 'passwd newuser',
    explanation: '`passwd <username>`으로 root는 다른 사용자의 비밀번호를 설정할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'NORMAL',
    title: '그룹 삭제',
    text: '`oldteam` 그룹을 삭제하는 명령어는?',
    answer: 'groupdel oldteam',
    explanation:
      '`groupdel`은 시스템에서 그룹을 삭제합니다. 기본 그룹으로 사용 중인 사용자가 있으면 삭제할 수 없습니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'NORMAL',
    title: '최근 로그인 이력',
    text: '시스템의 최근 로그인 이력을 확인하는 명령어는?',
    answer: 'last',
    explanation: '`last`는 `/var/log/wtmp` 파일을 읽어 최근 로그인/로그아웃 이력을 표시합니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'NORMAL',
    title: '사용자 다른 사용자로 전환',
    text: '`webadmin` 사용자로 전환하는 명령어는?',
    answer: 'su - webadmin',
    explanation:
      '`su - <username>`은 지정된 사용자로 전환하며, 해당 사용자의 환경변수를 로드합니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'NORMAL',
    title: '비밀번호 만료 설정',
    text: '`user1` 사용자의 비밀번호가 90일 후 만료되도록 설정하는 명령어는?',
    answer: 'chage -M 90 user1',
    explanation:
      '`chage -M`은 비밀번호의 최대 유효 기간(일)을 설정합니다. 만료 후 사용자는 비밀번호를 변경해야 합니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  // --- HARD (11) ---
  {
    difficulty: 'HARD',
    title: '비밀번호 정책 확인',
    text: '`user1` 사용자의 비밀번호 만료 정보를 확인하는 명령어는?',
    answer: 'chage -l user1',
    explanation:
      '`chage -l`은 비밀번호 최종 변경일, 만료일, 최소/최대 기간, 경고 기간 등을 표시합니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'HARD',
    title: 'sudoers 편집',
    text: 'sudo 권한을 안전하게 편집하는 명령어는?',
    answer: 'visudo',
    explanation:
      '`visudo`는 `/etc/sudoers` 파일을 문법 검사와 함께 편집합니다. 직접 편집하면 문법 오류로 sudo가 작동하지 않을 수 있습니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'HARD',
    title: '시스템 사용자 생성',
    text: '`appservice`라는 시스템 사용자를 로그인 불가 쉘로 생성하는 명령어는?',
    answer: 'useradd -r -s /usr/sbin/nologin appservice',
    explanation:
      '`-r`은 시스템 계정(낮은 UID), `-s /usr/sbin/nologin`은 로그인 불가 쉘을 지정합니다. 데몬 서비스용 계정에 사용됩니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'HARD',
    title: '실패한 로그인 확인',
    text: '실패한 로그인 시도 이력을 확인하는 명령어는?',
    answer: 'lastb',
    explanation:
      '`lastb`는 `/var/log/btmp` 파일을 읽어 실패한 로그인 시도를 표시합니다. 보안 감사에 중요합니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'HARD',
    title: '사용자 UID 지정 생성',
    text: 'UID를 1500으로 지정하여 `custom` 사용자를 생성하는 명령어는?',
    answer: 'useradd -u 1500 custom',
    explanation:
      '`-u`는 사용자의 UID를 직접 지정합니다. NFS 등에서 UID 일관성이 필요할 때 사용합니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'HARD',
    title: '다음 로그인 시 비밀번호 변경 강제',
    text: '`newuser` 사용자가 다음 로그인 시 반드시 비밀번호를 변경하도록 설정하는 명령어는?',
    answer: 'chage -d 0 newuser',
    explanation:
      '`chage -d 0`은 비밀번호의 마지막 변경일을 0(에포크)으로 설정하여 즉시 만료시킵니다. 다음 로그인 시 비밀번호 변경이 강제됩니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'HARD',
    title: 'sudo 비밀번호 없이',
    text: '`deploy` 사용자가 비밀번호 입력 없이 sudo를 사용할 수 있도록 sudoers에 추가할 항목은?',
    answer: 'deploy ALL=(ALL) NOPASSWD: ALL',
    explanation:
      '`NOPASSWD: ALL`은 비밀번호 확인 없이 모든 명령을 sudo로 실행할 수 있게 합니다. 자동화 스크립트에 사용됩니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'HARD',
    title: 'PAM 설정 확인',
    text: 'SSH 서비스의 PAM(Pluggable Authentication Module) 설정 파일 경로는?',
    answer: '/etc/pam.d/sshd',
    explanation:
      '`/etc/pam.d/sshd`는 SSH 서비스의 인증, 계정, 세션 관련 PAM 모듈 설정을 포함합니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'HARD',
    title: '사용자 기본 그룹 변경',
    text: '`developer` 사용자의 기본(primary) 그룹을 `engineering`으로 변경하는 명령어는?',
    answer: 'usermod -g engineering developer',
    explanation:
      '`usermod -g`는 사용자의 기본 그룹을 변경합니다. `-G`(보조 그룹)와 다르게 `-g`는 기본 그룹을 지정합니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'HARD',
    title: '사용자 홈 디렉토리 변경',
    text: '`user1` 사용자의 홈 디렉토리를 `/opt/user1`로 변경하고 기존 파일도 이동하는 명령어는?',
    answer: 'usermod -d /opt/user1 -m user1',
    explanation:
      '`-d`는 새 홈 디렉토리 경로, `-m`은 기존 홈 디렉토리의 내용을 새 경로로 이동합니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  {
    difficulty: 'HARD',
    title: '로그인 감사',
    text: '각 사용자의 마지막 로그인 시간을 확인하는 명령어는?',
    answer: 'lastlog',
    explanation:
      '`lastlog`는 `/var/log/lastlog` 파일을 읽어 모든 사용자의 마지막 로그인 시간과 터미널, 호스트를 표시합니다.',
    categoryId: 2,
    subCategoryId: 17,
  },
  // =============================================
  // Linux > Disk (categoryId: 2, subCategoryId: 18)
  // =============================================
  // --- EASY (11) ---
  {
    difficulty: 'EASY',
    title: '디스크 사용량 확인',
    text: '모든 파일 시스템의 디스크 사용량을 사람이 읽기 쉬운 형태로 확인하는 명령어는?',
    answer: 'df -h',
    explanation:
      '`df -h`(disk free, human-readable)는 각 파일 시스템의 전체 크기, 사용량, 남은 용량, 사용률을 보기 쉬운 단위로 표시합니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'EASY',
    title: '디렉토리 크기 확인',
    text: '`/var/log/` 디렉토리의 전체 크기를 확인하는 명령어는?',
    answer: 'du -sh /var/log/',
    explanation:
      '`du -sh`에서 `-s`는 총합(summary), `-h`는 사람이 읽기 쉬운 단위로 디렉토리 크기를 표시합니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'EASY',
    title: '블록 장치 목록',
    text: '시스템의 모든 블록 장치(디스크, 파티션)를 트리 형태로 확인하는 명령어는?',
    answer: 'lsblk',
    explanation:
      '`lsblk`(list block devices)는 디스크와 파티션을 트리 형태로 표시합니다. 크기, 타입, 마운트 포인트를 확인할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'EASY',
    title: '마운트 상태 확인',
    text: '현재 마운트된 모든 파일 시스템을 확인하는 명령어는?',
    answer: 'mount',
    explanation:
      '`mount`를 인자 없이 실행하면 현재 마운트된 모든 파일 시스템의 장치, 마운트 포인트, 타입, 옵션을 표시합니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'EASY',
    title: 'USB 마운트',
    text: '`/dev/sdb1` 장치를 `/mnt/usb`에 마운트하는 명령어는?',
    answer: 'mount /dev/sdb1 /mnt/usb',
    explanation: '`mount <device> <mount-point>`로 장치를 지정된 디렉토리에 마운트합니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'EASY',
    title: '마운트 해제',
    text: '`/mnt/usb`에 마운트된 장치를 마운트 해제하는 명령어는?',
    answer: 'umount /mnt/usb',
    explanation:
      '`umount`는 마운트된 파일 시스템을 해제합니다. 해당 디렉토리를 사용 중인 프로세스가 없어야 합니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'EASY',
    title: '하위 디렉토리 크기',
    text: '현재 디렉토리의 직속 하위 디렉토리별 크기를 확인하는 명령어는?',
    answer: 'du -h --max-depth=1',
    explanation:
      '`--max-depth=1`은 한 단계 깊이까지만 크기를 계산합니다. 어떤 디렉토리가 많은 공간을 차지하는지 파악할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'EASY',
    title: '스왑 사용량 확인',
    text: '스왑 파티션/파일의 사용량을 확인하는 명령어는?',
    answer: 'swapon --show',
    explanation: '`swapon --show`는 활성화된 스왑 영역의 파일명, 타입, 크기, 사용량을 표시합니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'EASY',
    title: '파일 시스템 타입 확인',
    text: '모든 마운트된 파일 시스템의 타입을 확인하는 명령어는?',
    answer: 'df -T',
    explanation: '`df -T`는 각 파일 시스템의 타입(ext4, xfs, tmpfs 등)을 함께 표시합니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'EASY',
    title: 'inode 사용량 확인',
    text: '파일 시스템의 inode 사용량을 확인하는 명령어는?',
    answer: 'df -i',
    explanation:
      '`df -i`는 각 파일 시스템의 전체 inode 수, 사용된 inode, 남은 inode를 표시합니다. inode가 부족하면 디스크 공간이 남아도 파일을 생성할 수 없습니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'EASY',
    title: '디스크 정보 확인',
    text: '`/dev/sda` 디스크의 파티션 테이블을 확인하는 명령어는?',
    answer: 'fdisk -l /dev/sda',
    explanation:
      '`fdisk -l`은 디스크의 파티션 테이블, 각 파티션의 크기, 타입, 시작/끝 섹터를 표시합니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  // --- NORMAL (11) ---
  {
    difficulty: 'NORMAL',
    title: '큰 디렉토리 찾기',
    text: '`/home` 하위에서 1GB 이상인 디렉토리를 찾아 크기 순으로 정렬하는 명령어는?',
    answer: 'du -h /home --max-depth=2 | sort -rh | head -20',
    explanation:
      '`du`로 크기를 계산하고, `sort -rh`로 크기 내림차순 정렬, `head -20`으로 상위 20개를 표시합니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'NORMAL',
    title: 'ext4 파일 시스템 생성',
    text: '`/dev/sdb1` 파티션에 ext4 파일 시스템을 생성하는 명령어는?',
    answer: 'mkfs.ext4 /dev/sdb1',
    explanation:
      '`mkfs.ext4`는 파티션에 ext4 파일 시스템을 생성(포맷)합니다. 기존 데이터는 모두 삭제됩니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'NORMAL',
    title: '읽기 전용 마운트',
    text: '`/dev/sdb1`을 `/mnt/backup`에 읽기 전용으로 마운트하는 명령어는?',
    answer: 'mount -o ro /dev/sdb1 /mnt/backup',
    explanation:
      '`-o ro`(read-only)는 파일 시스템을 읽기 전용으로 마운트합니다. 데이터 보호가 필요한 백업 디스크에 유용합니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'NORMAL',
    title: '파일 시스템 검사',
    text: '`/dev/sda1` 파티션의 파일 시스템 무결성을 검사하는 명령어는?',
    answer: 'fsck /dev/sda1',
    explanation:
      '`fsck`(file system check)는 파일 시스템의 무결성을 검사하고 오류를 복구합니다. 마운트 해제 상태에서 실행해야 합니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'NORMAL',
    title: 'fstab 확인',
    text: '시스템 부팅 시 자동 마운트 설정을 확인하는 파일 경로는?',
    answer: 'cat /etc/fstab',
    explanation:
      '`/etc/fstab`에는 부팅 시 자동으로 마운트할 파일 시스템의 장치, 마운트 포인트, 타입, 옵션이 설정되어 있습니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'NORMAL',
    title: '스왑 파일 생성',
    text: '1GB 크기의 스왑 파일 `/swapfile`을 생성하는 명령어는?',
    answer: 'dd if=/dev/zero of=/swapfile bs=1M count=1024',
    explanation: '`dd`로 `/dev/zero`에서 1MB 블록을 1024개 읽어 1GB 크기의 파일을 생성합니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'NORMAL',
    title: '스왑 활성화',
    text: '`/swapfile`을 스왑 영역으로 초기화하고 활성화하는 두 명령어는?',
    answer: 'mkswap /swapfile && swapon /swapfile',
    explanation: '`mkswap`은 파일을 스왑 영역으로 초기화하고, `swapon`은 해당 스왑을 활성화합니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'NORMAL',
    title: 'tmpfs 마운트',
    text: '512MB 크기의 tmpfs를 `/mnt/ramdisk`에 마운트하는 명령어는?',
    answer: 'mount -t tmpfs -o size=512M tmpfs /mnt/ramdisk',
    explanation: '`tmpfs`는 메모리 기반 파일 시스템으로, 매우 빠른 임시 저장소를 제공합니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'NORMAL',
    title: '디스크 I/O 모니터링',
    text: '디스크별 I/O 통계를 2초 간격으로 확인하는 명령어는?',
    answer: 'iostat 2',
    explanation:
      '`iostat 2`는 2초 간격으로 각 디스크의 읽기/쓰기 속도, 처리량, 대기 시간을 표시합니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'NORMAL',
    title: 'ncdu 디스크 분석',
    text: '인터랙티브하게 디렉토리별 디스크 사용량을 분석하는 명령어는?',
    answer: 'ncdu /',
    explanation:
      '`ncdu`는 ncurses 기반의 디스크 사용량 분석 도구로, 디렉토리를 탐색하며 크기를 확인하고 파일을 삭제할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'NORMAL',
    title: 'UUID로 마운트',
    text: '`/dev/sdb1`의 UUID를 확인하는 명령어는?',
    answer: 'blkid /dev/sdb1',
    explanation:
      '`blkid`는 블록 장치의 UUID, 파일 시스템 타입, 라벨을 표시합니다. UUID는 `/etc/fstab`에서 장치 식별에 사용됩니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  // --- HARD (11) ---
  {
    difficulty: 'HARD',
    title: 'LVM 물리 볼륨 생성',
    text: '`/dev/sdb`를 LVM 물리 볼륨으로 초기화하는 명령어는?',
    answer: 'pvcreate /dev/sdb',
    explanation:
      '`pvcreate`는 디스크나 파티션을 LVM 물리 볼륨(PV)으로 초기화합니다. LVM 사용의 첫 단계입니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'HARD',
    title: 'LVM 볼륨 그룹 생성',
    text: '`/dev/sdb`와 `/dev/sdc`를 `vg_data`라는 볼륨 그룹으로 생성하는 명령어는?',
    answer: 'vgcreate vg_data /dev/sdb /dev/sdc',
    explanation:
      '`vgcreate`는 물리 볼륨을 묶어 볼륨 그룹(VG)을 생성합니다. 여러 디스크의 공간을 하나로 통합할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'HARD',
    title: 'LVM 논리 볼륨 생성',
    text: '`vg_data` 볼륨 그룹에서 50GB 크기의 `lv_app` 논리 볼륨을 생성하는 명령어는?',
    answer: 'lvcreate -L 50G -n lv_app vg_data',
    explanation:
      '`lvcreate -L`은 크기, `-n`은 이름을 지정합니다. 논리 볼륨은 `/dev/vg_data/lv_app`으로 접근됩니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'HARD',
    title: 'LVM 볼륨 확장',
    text: '`/dev/vg_data/lv_app` 논리 볼륨을 10GB 더 확장하는 명령어는?',
    answer: 'lvextend -L +10G /dev/vg_data/lv_app',
    explanation:
      '`lvextend -L +10G`는 논리 볼륨의 크기를 10GB 추가합니다. 이후 `resize2fs`(ext4)로 파일 시스템도 확장해야 합니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'HARD',
    title: '파일 시스템 확장',
    text: '확장된 `/dev/vg_data/lv_app`의 ext4 파일 시스템을 볼륨 크기에 맞게 확장하는 명령어는?',
    answer: 'resize2fs /dev/vg_data/lv_app',
    explanation:
      '`resize2fs`는 ext2/ext3/ext4 파일 시스템의 크기를 조정합니다. 인자 없이 실행하면 파티션 전체 크기로 확장합니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'HARD',
    title: 'RAID 배열 확인',
    text: '시스템의 소프트웨어 RAID 배열 상태를 확인하는 명령어는?',
    answer: 'cat /proc/mdstat',
    explanation:
      '`/proc/mdstat`은 모든 MD(Multiple Devices) RAID 배열의 상태, 구성, 동기화 진행 상황을 보여줍니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'HARD',
    title: '디스크 성능 테스트',
    text: '`/dev/sda`의 순차 읽기 속도를 테스트하는 명령어는?',
    answer: 'hdparm -tT /dev/sda',
    explanation: '`hdparm -tT`는 `-t`로 디스크 읽기 속도, `-T`로 캐시 읽기 속도를 측정합니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'HARD',
    title: 'TRIM 실행',
    text: 'SSD의 모든 마운트된 파일 시스템에 TRIM 명령을 실행하는 명령어는?',
    answer: 'fstrim -a',
    explanation:
      '`fstrim -a`는 모든 마운트된 파일 시스템에 TRIM을 실행하여 SSD에서 사용하지 않는 블록을 해제합니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'HARD',
    title: 'XFS 파일 시스템 확장',
    text: '`/data`에 마운트된 XFS 파일 시스템을 확장하는 명령어는?',
    answer: 'xfs_growfs /data',
    explanation:
      '`xfs_growfs`는 마운트된 XFS 파일 시스템을 실시간으로 확장합니다. XFS는 축소를 지원하지 않습니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'HARD',
    title: '디스크 사용량 쿼터 설정',
    text: '`user1` 사용자의 디스크 쿼터를 편집하는 명령어는?',
    answer: 'edquota user1',
    explanation: '`edquota`는 사용자의 디스크 사용량 제한(소프트/하드 리밋)을 에디터로 편집합니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  {
    difficulty: 'HARD',
    title: 'LVM 스냅샷 생성',
    text: '`/dev/vg_data/lv_app`의 5GB 크기 스냅샷을 `lv_app_snap`으로 생성하는 명령어는?',
    answer: 'lvcreate -L 5G -s -n lv_app_snap /dev/vg_data/lv_app',
    explanation:
      '`-s`(snapshot)는 스냅샷 볼륨을 생성합니다. 원본 볼륨의 특정 시점 상태를 보존하며, 백업이나 테스트에 사용됩니다.',
    categoryId: 2,
    subCategoryId: 18,
  },
  // =============================================
  // Linux > Package (categoryId: 2, subCategoryId: 19)
  // =============================================
  // --- EASY (11) ---
  {
    difficulty: 'EASY',
    title: '패키지 목록 업데이트',
    text: 'APT 패키지 목록을 최신 상태로 업데이트하는 명령어는?',
    answer: 'apt update',
    explanation:
      '`apt update`는 패키지 저장소에서 최신 패키지 목록을 다운로드합니다. 패키지를 설치하기 전에 항상 실행하는 것이 좋습니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'EASY',
    title: '패키지 설치',
    text: '`nginx` 패키지를 설치하는 명령어는?',
    answer: 'apt install nginx',
    explanation: '`apt install`은 지정된 패키지와 의존성 패키지를 함께 설치합니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'EASY',
    title: '패키지 삭제',
    text: '`nginx` 패키지를 삭제하는 명령어는?',
    answer: 'apt remove nginx',
    explanation: '`apt remove`는 패키지를 삭제하지만, 설정 파일은 남겨둡니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'EASY',
    title: '전체 패키지 업그레이드',
    text: '설치된 모든 패키지를 최신 버전으로 업그레이드하는 명령어는?',
    answer: 'apt upgrade',
    explanation: '`apt upgrade`는 설치된 패키지 중 새 버전이 있는 것을 모두 업그레이드합니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'EASY',
    title: '패키지 검색',
    text: '패키지 이름에 "python"이 포함된 패키지를 검색하는 명령어는?',
    answer: 'apt search python',
    explanation: '`apt search`는 패키지 이름과 설명에서 키워드를 검색합니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'EASY',
    title: '패키지 정보 확인',
    text: '`nginx` 패키지의 상세 정보(버전, 설명, 의존성 등)를 확인하는 명령어는?',
    answer: 'apt show nginx',
    explanation: '`apt show`는 패키지의 버전, 크기, 의존성, 설명 등 상세 정보를 표시합니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'EASY',
    title: '설치된 패키지 목록',
    text: '현재 시스템에 설치된 모든 패키지를 나열하는 명령어는?',
    answer: 'apt list --installed',
    explanation: '`apt list --installed`는 현재 설치된 모든 패키지와 버전을 표시합니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'EASY',
    title: 'YUM 패키지 설치',
    text: 'YUM 패키지 매니저로 `httpd` 패키지를 설치하는 명령어는?',
    answer: 'yum install httpd',
    explanation: '`yum install`은 RHEL/CentOS 계열에서 패키지를 설치합니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'EASY',
    title: '확인 없이 설치',
    text: '`curl` 패키지를 확인 프롬프트 없이 바로 설치하는 명령어는?',
    answer: 'apt install -y curl',
    explanation:
      '`-y`(yes) 옵션은 설치 확인 프롬프트에 자동으로 "yes"로 응답합니다. 스크립트 자동화에 유용합니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'EASY',
    title: '업그레이드 가능 패키지 확인',
    text: '업그레이드 가능한 패키지 목록을 확인하는 명령어는?',
    answer: 'apt list --upgradable',
    explanation: '`apt list --upgradable`은 새 버전이 있는 설치된 패키지를 나열합니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'EASY',
    title: 'DNF 패키지 설치',
    text: 'DNF 패키지 매니저로 `git`을 설치하는 명령어는?',
    answer: 'dnf install git',
    explanation: '`dnf`는 RHEL 8+/Fedora에서 `yum`을 대체하는 패키지 매니저입니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  // --- NORMAL (11) ---
  {
    difficulty: 'NORMAL',
    title: '설정 파일 포함 삭제',
    text: '`nginx` 패키지를 설정 파일까지 완전히 삭제하는 명령어는?',
    answer: 'apt purge nginx',
    explanation:
      '`apt purge`는 패키지와 함께 설정 파일까지 모두 삭제합니다. `remove`는 설정 파일을 남겨둡니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'NORMAL',
    title: '불필요 패키지 정리',
    text: '더 이상 필요 없는 의존성 패키지를 자동으로 삭제하는 명령어는?',
    answer: 'apt autoremove',
    explanation:
      '`apt autoremove`는 다른 패키지의 의존성으로 설치되었지만 더 이상 필요하지 않은 패키지를 자동 삭제합니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'NORMAL',
    title: 'deb 파일 설치',
    text: '다운로드한 `package.deb` 파일을 설치하는 명령어는?',
    answer: 'dpkg -i package.deb',
    explanation:
      '`dpkg -i`는 로컬 `.deb` 파일을 직접 설치합니다. 의존성 문제가 있으면 `apt install -f`로 해결할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'NORMAL',
    title: '패키지가 제공하는 파일 확인',
    text: '`nginx` 패키지가 설치하는 파일 목록을 확인하는 명령어는?',
    answer: 'dpkg -L nginx',
    explanation: '`dpkg -L`은 설치된 패키지가 제공하는 모든 파일의 경로를 나열합니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'NORMAL',
    title: '파일의 패키지 확인',
    text: '`/usr/bin/vim` 파일이 어떤 패키지에서 제공되는지 확인하는 명령어는?',
    answer: 'dpkg -S /usr/bin/vim',
    explanation: '`dpkg -S`는 지정된 파일이 어떤 패키지에 포함되어 있는지 찾습니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'NORMAL',
    title: '특정 버전 설치',
    text: '`nodejs` 패키지의 특정 버전 `18.0.0-1`을 설치하는 명령어는?',
    answer: 'apt install nodejs=18.0.0-1',
    explanation: '`패키지명=버전`으로 특정 버전을 지정하여 설치할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'NORMAL',
    title: '패키지 캐시 정리',
    text: 'APT 캐시에 저장된 다운로드된 패키지 파일을 모두 삭제하는 명령어는?',
    answer: 'apt clean',
    explanation:
      '`apt clean`은 `/var/cache/apt/archives/`의 모든 패키지 파일을 삭제하여 디스크 공간을 확보합니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'NORMAL',
    title: 'RPM 파일 설치',
    text: 'RHEL 계열에서 `package.rpm` 파일을 설치하는 명령어는?',
    answer: 'rpm -ivh package.rpm',
    explanation: '`rpm -ivh`에서 `-i`는 설치, `-v`는 상세 출력, `-h`는 진행률 표시입니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'NORMAL',
    title: '패키지 다운로드만',
    text: '`nginx` 패키지를 설치하지 않고 `.deb` 파일만 다운로드하는 명령어는?',
    answer: 'apt download nginx',
    explanation:
      '`apt download`는 패키지의 `.deb` 파일을 현재 디렉토리에 다운로드만 하고 설치하지 않습니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'NORMAL',
    title: '의존성 확인',
    text: '`nginx` 패키지의 의존성 목록을 확인하는 명령어는?',
    answer: 'apt depends nginx',
    explanation:
      '`apt depends`는 패키지가 의존하는 다른 패키지, 추천 패키지, 충돌 패키지를 표시합니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'NORMAL',
    title: '패키지 버전 고정',
    text: '`nodejs` 패키지가 자동 업그레이드되지 않도록 고정(hold)하는 명령어는?',
    answer: 'apt-mark hold nodejs',
    explanation:
      '`apt-mark hold`는 패키지를 현재 버전으로 고정합니다. `apt upgrade` 시 해당 패키지는 업그레이드되지 않습니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  // --- HARD (11) ---
  {
    difficulty: 'HARD',
    title: 'PPA 저장소 추가',
    text: '`ppa:deadsnakes/ppa` PPA 저장소를 추가하는 명령어는?',
    answer: 'add-apt-repository ppa:deadsnakes/ppa',
    explanation:
      '`add-apt-repository`는 PPA(Personal Package Archive) 저장소를 시스템에 추가합니다. 이후 `apt update`로 패키지 목록을 갱신해야 합니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'HARD',
    title: 'GPG 키 추가',
    text: '`https://example.com/key.gpg`에서 APT 저장소 GPG 키를 다운로드하여 추가하는 명령어는?',
    answer:
      'curl -fsSL https://example.com/key.gpg | gpg --dearmor -o /etc/apt/keyrings/example.gpg',
    explanation:
      '`gpg --dearmor`는 ASCII-armored GPG 키를 바이너리 형식으로 변환하여 저장합니다. APT 저장소 인증에 사용됩니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'HARD',
    title: '커스텀 저장소 추가',
    text: 'APT 소스 리스트에 새로운 저장소를 추가하기 위해 생성/편집해야 하는 파일 경로 형식은?',
    answer: '/etc/apt/sources.list.d/',
    explanation:
      '`/etc/apt/sources.list.d/` 디렉토리에 `.list` 또는 `.sources` 파일을 생성하여 커스텀 저장소를 추가합니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'HARD',
    title: '패키지 재설정',
    text: '`postfix` 패키지의 설정을 대화형으로 재설정하는 명령어는?',
    answer: 'dpkg-reconfigure postfix',
    explanation:
      '`dpkg-reconfigure`는 이미 설치된 패키지의 설정을 처음 설치할 때의 대화형 설정 마법사로 다시 실행합니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'HARD',
    title: '패키지 빌드 의존성 설치',
    text: '소스 패키지의 빌드 의존성을 자동으로 설치하는 명령어는?',
    answer: 'apt build-dep nginx',
    explanation:
      '`apt build-dep`은 소스 패키지를 빌드하는 데 필요한 모든 의존성 패키지를 설치합니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'HARD',
    title: '깨진 패키지 복구',
    text: '깨진 의존성 관계를 자동으로 복구하는 명령어는?',
    answer: 'apt install -f',
    explanation:
      '`apt install -f`(fix-broken)는 충족되지 않은 의존성을 해결하기 위해 필요한 패키지를 설치하거나 문제 패키지를 제거합니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'HARD',
    title: 'Snap 패키지 설치',
    text: 'Snap으로 `code` 패키지를 클래식 격리 모드로 설치하는 명령어는?',
    answer: 'snap install code --classic',
    explanation:
      '`--classic`은 Snap의 격리 제한 없이 시스템에 전체 접근을 허용합니다. IDE 등 시스템 접근이 필요한 앱에 사용됩니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'HARD',
    title: '패키지 고정 해제',
    text: '`nodejs` 패키지의 버전 고정(hold)을 해제하는 명령어는?',
    answer: 'apt-mark unhold nodejs',
    explanation:
      '`apt-mark unhold`는 패키지의 버전 고정을 해제하여 다시 업그레이드 대상에 포함시킵니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'HARD',
    title: 'RPM 패키지 내용 확인',
    text: 'RPM 파일 `package.rpm`의 포함된 파일 목록을 설치 없이 확인하는 명령어는?',
    answer: 'rpm -qlp package.rpm',
    explanation:
      '`rpm -qlp`에서 `-q`는 질의, `-l`은 파일 목록, `-p`는 설치되지 않은 패키지 파일을 대상으로 합니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'HARD',
    title: '패키지 다운그레이드',
    text: 'APT로 `nginx` 패키지를 이전 버전으로 다운그레이드하기 위해 설치 가능한 버전 목록을 확인하는 명령어는?',
    answer: 'apt list -a nginx',
    explanation:
      '`apt list -a`는 저장소에서 사용 가능한 모든 버전을 표시합니다. 원하는 버전을 `apt install nginx=버전`으로 설치할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  {
    difficulty: 'HARD',
    title: '보안 업데이트만 적용',
    text: 'Ubuntu에서 보안 업데이트만 설치하는 명령어는?',
    answer:
      'apt upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"',
    explanation:
      '`unattended-upgrades`를 사용하거나, APT 옵션으로 설정 파일 충돌을 자동 처리하며 업그레이드할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 19,
  },
  // =============================================
  // Linux > Cron (categoryId: 2, subCategoryId: 20)
  // =============================================
  // --- EASY (11) ---
  {
    difficulty: 'EASY',
    title: 'crontab 편집',
    text: '현재 사용자의 cron 작업을 편집하는 명령어는?',
    answer: 'crontab -e',
    explanation:
      '`crontab -e`는 현재 사용자의 crontab 파일을 기본 에디터로 열어 예약 작업을 편집할 수 있게 합니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'EASY',
    title: 'crontab 목록 확인',
    text: '현재 사용자에게 등록된 cron 작업 목록을 확인하는 명령어는?',
    answer: 'crontab -l',
    explanation: '`crontab -l`은 현재 사용자의 모든 cron 작업을 표시합니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'EASY',
    title: 'crontab 삭제',
    text: '현재 사용자의 모든 cron 작업을 삭제하는 명령어는?',
    answer: 'crontab -r',
    explanation:
      '`crontab -r`은 현재 사용자의 crontab을 완전히 삭제합니다. 복구할 수 없으므로 주의가 필요합니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'EASY',
    title: '매일 자정 실행',
    text: '매일 자정(00:00)에 `/home/user/backup.sh`를 실행하는 cron 표현식은?',
    answer: '0 0 * * * /home/user/backup.sh',
    explanation:
      '`0 0 * * *`에서 첫 번째 0은 분(0분), 두 번째 0은 시(0시)이며, 나머지 `*`은 매일, 매월, 매요일을 의미합니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'EASY',
    title: '매시 정각 실행',
    text: '매시간 정각에 `curl https://example.com/health`를 실행하는 cron 표현식은?',
    answer: '0 * * * * curl https://example.com/health',
    explanation: '`0 * * * *`는 매시간 0분, 즉 정각마다 실행됩니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'EASY',
    title: 'cron 필드 순서',
    text: 'cron 표현식의 5개 필드 순서는?',
    answer: '분 시 일 월 요일',
    explanation:
      'cron 표현식은 왼쪽부터 분(0-59), 시(0-23), 일(1-31), 월(1-12), 요일(0-7, 0과 7은 일요일) 순서입니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'EASY',
    title: '매주 월요일 실행',
    text: '매주 월요일 오전 9시에 `/opt/report.sh`를 실행하는 cron 표현식은?',
    answer: '0 9 * * 1 /opt/report.sh',
    explanation: '요일 필드에서 `1`은 월요일입니다. (0=일, 1=월, ..., 6=토, 7=일)',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'EASY',
    title: '매분 실행',
    text: '1분마다 `/tmp/check.sh`를 실행하는 cron 표현식은?',
    answer: '* * * * * /tmp/check.sh',
    explanation: '모든 필드가 `*`이면 매분(1분 간격)으로 실행됩니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'EASY',
    title: '시스템 cron 확인',
    text: '시스템 전역 cron 작업이 설정된 파일 경로는?',
    answer: '/etc/crontab',
    explanation:
      '`/etc/crontab`은 시스템 전역 cron 설정 파일로, 사용자 필드가 추가로 포함되어 있습니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'EASY',
    title: '다른 사용자 crontab 확인',
    text: 'root로서 `webuser` 사용자의 cron 작업을 확인하는 명령어는?',
    answer: 'crontab -u webuser -l',
    explanation:
      '`-u` 옵션으로 다른 사용자의 crontab을 확인하거나 편집할 수 있습니다. root 권한이 필요합니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'EASY',
    title: '매월 1일 실행',
    text: '매월 1일 오전 3시에 `/opt/monthly.sh`를 실행하는 cron 표현식은?',
    answer: '0 3 1 * * /opt/monthly.sh',
    explanation: '일 필드가 `1`이면 매월 1일에 실행됩니다. `0 3`은 오전 3시 0분을 의미합니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  // --- NORMAL (11) ---
  {
    difficulty: 'NORMAL',
    title: '5분 간격 실행',
    text: '5분마다 `/opt/monitor.sh`를 실행하는 cron 표현식은?',
    answer: '*/5 * * * * /opt/monitor.sh',
    explanation: '`*/5`는 5분 간격을 의미합니다. 0, 5, 10, 15, ... 분에 실행됩니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'NORMAL',
    title: '업무 시간 실행',
    text: '평일(월~금) 오전 9시부터 오후 6시까지 매시간 정각에 실행하는 cron 표현식은?',
    answer: '0 9-18 * * 1-5 /opt/hourly.sh',
    explanation: '`9-18`은 9시부터 18시까지, `1-5`는 월요일부터 금요일까지의 범위를 나타냅니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'NORMAL',
    title: '출력 리다이렉션',
    text: '매일 오전 2시에 `backup.sh`를 실행하고 로그를 `/var/log/backup.log`에 저장하는 cron 표현식은?',
    answer: '0 2 * * * /opt/backup.sh >> /var/log/backup.log 2>&1',
    explanation:
      '`>> /var/log/backup.log 2>&1`은 표준 출력과 에러를 모두 로그 파일에 추가합니다. cron은 기본적으로 출력을 메일로 보냅니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'NORMAL',
    title: 'cron 메일 비활성화',
    text: 'cron 작업의 출력 메일을 비활성화하려면 어떤 환경변수를 설정해야 하는가?',
    answer: 'MAILTO=""',
    explanation: 'crontab 상단에 `MAILTO=""`를 추가하면 cron의 출력 메일이 비활성화됩니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'NORMAL',
    title: '특정 월에만 실행',
    text: '1월과 7월의 1일 오전 0시에 실행하는 cron 표현식은?',
    answer: '0 0 1 1,7 * /opt/semiannual.sh',
    explanation: '월 필드에 `1,7`은 1월과 7월을 의미합니다. 쉼표로 여러 값을 나열할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'NORMAL',
    title: 'cron.d 디렉토리',
    text: '시스템 cron 작업 파일을 개별적으로 관리하는 디렉토리 경로는?',
    answer: '/etc/cron.d/',
    explanation:
      '`/etc/cron.d/`에 개별 파일로 cron 작업을 설정할 수 있습니다. 패키지별로 cron 작업을 분리 관리할 때 유용합니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'NORMAL',
    title: '환경변수 설정',
    text: 'cron 작업에서 `PATH`를 `/usr/local/bin:/usr/bin:/bin`으로 설정하는 방법은?',
    answer: 'PATH=/usr/local/bin:/usr/bin:/bin',
    explanation:
      'crontab 상단에 `PATH=...`를 추가합니다. cron은 기본 PATH가 매우 제한적이므로 필요한 경로를 명시해야 합니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'NORMAL',
    title: 'anacron 확인',
    text: '시스템이 꺼져있다 켜졌을 때 놓친 작업을 실행하는 anacron의 설정 파일은?',
    answer: '/etc/anacrontab',
    explanation:
      '`/etc/anacrontab`은 anacron 설정 파일입니다. 시스템이 꺼져있는 동안 놓친 작업을 다음 부팅 시 실행합니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'NORMAL',
    title: '일/시간 cron 디렉토리',
    text: '매일 실행할 스크립트를 넣는 시스템 cron 디렉토리는?',
    answer: '/etc/cron.daily/',
    explanation:
      '`/etc/cron.daily/`에 실행 가능한 스크립트를 넣으면 매일 자동으로 실행됩니다. hourly, weekly, monthly 디렉토리도 있습니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'NORMAL',
    title: '30분 간격 실행',
    text: '30분마다 스크립트를 실행하는 cron 표현식은?',
    answer: '*/30 * * * * /opt/check.sh',
    explanation: '`*/30`은 30분 간격을 의미합니다. 매시 0분과 30분에 실행됩니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'NORMAL',
    title: 'cron 서비스 상태',
    text: 'cron 서비스가 정상적으로 실행 중인지 확인하는 명령어는?',
    answer: 'systemctl status cron',
    explanation:
      '`systemctl status cron`으로 cron 데몬의 실행 상태를 확인합니다. 배포판에 따라 `crond`일 수 있습니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  // --- HARD (11) ---
  {
    difficulty: 'HARD',
    title: '복합 스케줄',
    text: '매주 화요일과 목요일 오후 2시 30분에 실행하는 cron 표현식은?',
    answer: '30 14 * * 2,4 /opt/biweekly.sh',
    explanation: '`30 14`는 14시 30분, `2,4`는 화요일(2)과 목요일(4)입니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'HARD',
    title: '@reboot 활용',
    text: '시스템 부팅 시 한 번만 `/opt/startup.sh`를 실행하는 cron 표현식은?',
    answer: '@reboot /opt/startup.sh',
    explanation:
      '`@reboot`은 시스템 부팅 시 한 번 실행되는 특수 스케줄입니다. 서비스 등록 없이 부팅 시 스크립트를 실행할 때 유용합니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'HARD',
    title: '파일 잠금으로 중복 방지',
    text: 'cron 작업이 이전 실행이 끝나지 않았을 때 중복 실행되지 않도록 `flock`을 사용하는 방법은?',
    answer: '* * * * * flock -n /tmp/job.lock /opt/job.sh',
    explanation:
      '`flock -n`은 잠금 파일을 획득하지 못하면 즉시 종료합니다. 이전 실행이 진행 중이면 새 실행이 건너뛰어집니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'HARD',
    title: 'cron 로그 확인',
    text: 'cron 작업의 실행 로그를 확인하는 명령어는?',
    answer: 'grep CRON /var/log/syslog',
    explanation:
      '`/var/log/syslog`에서 CRON 관련 로그를 필터링합니다. cron 작업의 실행 시간과 명령을 확인할 수 있습니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'HARD',
    title: 'systemd 타이머 생성',
    text: 'cron 대신 systemd 타이머를 사용할 때, 타이머 유닛 파일의 확장자는?',
    answer: '.timer',
    explanation:
      'systemd 타이머는 `.timer` 확장자의 유닛 파일로 정의됩니다. 대응하는 `.service` 파일이 함께 필요합니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'HARD',
    title: '사용자별 cron 제한',
    text: '특정 사용자의 cron 사용을 차단하기 위해 편집해야 하는 파일은?',
    answer: '/etc/cron.deny',
    explanation:
      '`/etc/cron.deny`에 사용자명을 추가하면 해당 사용자의 cron 사용이 차단됩니다. `/etc/cron.allow`가 존재하면 여기에 있는 사용자만 허용됩니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'HARD',
    title: '랜덤 지연 실행',
    text: 'cron 작업 실행 시 0~60초의 랜덤 지연을 추가하는 방법은?',
    answer: '0 * * * * sleep $((RANDOM \\% 60)) && /opt/job.sh',
    explanation:
      '`sleep $((RANDOM % 60))`는 0~59초의 랜덤 대기 후 명령을 실행합니다. 여러 서버가 동시에 실행하는 것을 분산할 때 유용합니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'HARD',
    title: 'at 일회성 예약',
    text: '오후 5시에 `shutdown -h now`를 일회성으로 예약하는 명령어는?',
    answer: 'echo "shutdown -h now" | at 17:00',
    explanation:
      '`at`은 지정된 시간에 명령을 한 번만 실행합니다. cron과 달리 반복 실행이 아닌 일회성 작업에 사용됩니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'HARD',
    title: 'at 작업 목록',
    text: '`at`으로 예약된 작업 목록을 확인하는 명령어는?',
    answer: 'atq',
    explanation: '`atq`는 현재 예약된 `at` 작업의 ID, 실행 시간, 큐를 표시합니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'HARD',
    title: 'systemd 타이머 활성화',
    text: '`backup.timer` systemd 타이머를 활성화하고 시작하는 명령어는?',
    answer: 'systemctl enable --now backup.timer',
    explanation: '`enable --now`는 타이머를 부팅 시 자동 시작으로 등록하고 즉시 시작합니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
  {
    difficulty: 'HARD',
    title: 'cron 특수 문자열',
    text: '`@hourly`과 동일한 의미의 cron 표현식 5개 필드는?',
    answer: '0 * * * *',
    explanation:
      '`@hourly`는 `0 * * * *`의 축약형으로 매시간 0분에 실행됩니다. `@daily`=`0 0 * * *`, `@weekly`=`0 0 * * 0` 등의 축약형이 있습니다.',
    categoryId: 2,
    subCategoryId: 20,
  },
];
