name: orvit-server-dev

on:
  push:
    branches: [feature/issue-2]

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.meta.outputs.short_sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      
      - uses: pnpm/action-setup@v3
        with:
          version: 9 
          run_install: false

      - uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
            
      - name: Create .env file
        run: |
          printf "PORT=%s\n" "${{ secrets.PORT }}" >> .env
          printf "DATABASE_URL=%s\n" "${{ secrets.DATABASE_URL }}" >> .env

      - name: Install & Build
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.dev
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}:dev-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  cd:
    runs-on: ubuntu-latest
    needs: ci 
    steps:
      - name: Get Runner IP
        id: ip
        run: echo "ipv4=$(curl -s https://ifconfig.me)" >> $GITHUB_OUTPUT

      - name: Install OCI CLI
        uses: oracle-actions/setup-oci-cli@v1
        with:
          user: ${{ secrets.OCI_USER_OCID }}
          tenancy: ${{ secrets.OCI_TENANCY_OCID }}
          fingerprint: ${{ secrets.OCI_FINGERPRINT }}
          region: ${{ secrets.OCI_REGION }}
          private_key: ${{ secrets.OCI_PRIVATE_KEY }}

      - name: Open Port 22 for Runner IP
        run: |
          oci network nsg rules add \
            --nsg-id ${{ secrets.OCI_NSG_ID }} \
            --security-rules '[{"direction": "INGRESS", "protocol": "6", "source": "${{ steps.ip.outputs.ipv4 }}/32", "source-type": "CIDR", "tcp-options": {"destination-port-range": {"max": 22, "min": 22}}, "description": "GHA-TEMP-${{ github.run_id }}"}]'

      - name: Run Deploy Script (SSH)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /opt/orbit/docker
            sudo ./deploy.sh

      - name: Close Port 22 (Remove NSG Rule)
        if: always() 
        run: |
          RULE_ID=$(oci network nsg rules list --nsg-id ${{ secrets.OCI_NSG_ID }} \
            --query "data[?description=='GHA-TEMP-${{ github.run_id }}'].id | [0]" --raw-output)
          
          if [ "$RULE_ID" != "null" ]; then
            oci network nsg rules remove --nsg-id ${{ secrets.OCI_NSG_ID }} --security-rule-ids "[\"$RULE_ID\"]" --force
          fi